### ISSUE TITLE
Backwards slash as directory separator on windows web servers.

### ISSUE THREAD

**Issue by Smart-Core** [helios-ag/FMElfinderBundle#113]
Then click on file "example.jpg" in path: "uploads" in tinymce filemanager, it's generate address "/uploads\example.jpg"

**Comment by helios-ag** [comment]
Hi @Smart-Core, 
Can you investigate causes of this behavior? Because my primary development platform is linux.

**Comment by nicolasmure** [comment]
Hi, maybe some statics slashes (or backslashes) have to be replaced with [`DIRECTORY_SEPARATOR`](http://php.net/manual/en/dir.constants.php) ?

**Comment by helios-ag** [comment]
Ping @Smart-Core, any comemnts on this?

**Comment by Smart-Core** [comment]
I'm using this patch https://github.com/Smart-Core/CMS-Sandbox/blob/master/app/Resources/FMElfinderBundle/views/Elfinder/helper/_tinymce4.html.twig#L12
