### ISSUE TITLE
Path issues and upload

### ISSUE THREAD

**Issue by Stony2k** [helios-ag/FMElfinderBundle#118]
Hello,

perhaps anybody can help me with some small problems.

1.) When i upload a file to S3 with the aws_s3_v2 connector he upload the file but after uploading i get an error and the site isn't reloading. Has anybody an idea how to solve that problem? 

2.) When i see the image and i double click on  that image the image is inserted to my ckeditor but the URL is missing he enter only "//name.jpg" how can i set the S3 domain?

Best regards,

René

**Comment by Stony2k** [comment]
Ok i have found the solution how to set the URL. I would be very well if there is a part in the documentation how to set the URL.

**Comment by helios-ag** [comment]
You can send PR with updated version of Readme :)

**Comment by Stony2k** [comment]
Yes i can try it but first if i have fixed the following problem :) 

Its the same problem i have descripted on top. If the upload is finished i get an error that the backend is not connected. In the profiler i can see the following problems. 

```
Warning: fclose(): 589 is not a valid stream resource

in vendor/helios-ag/fm-elfinder-php-connector/src/ElFinder.php at line 1599   -
            fclose($fp);
            if (! is_uploaded_file($tmpname) && @ unlink($tmpname)) unset($GLOBALS['elFinderTempFiles'][$tmpname]);
            $result['added'][] = $file;
        }
```

any ideas what could be wrong? The file is uploaded. If i reload the page i can see the file.

**Comment by helios-ag** [comment]
Need to check nao-pon fork and barryvdh fork too, maybe it was a bug that already fixed

**Comment by Stony2k** [comment]
:) that would be great ... i have changed the README with some informations how to setup S3. But if that is working its a really cool solution.

**Comment by Stony2k** [comment]
I have fixed that problem and have made an PR.

https://github.com/helios-ag/ElFinderPHP/pull/17

**Comment by Stony2k** [comment]
I think your can close this Ticket :) but the S3 driver isn't working well.

**Comment by helios-ag** [comment]
Sad to know :-( , hope it will be fixed soon.
