### ISSUE TITLE
S3 folder not shown after creation

### ISSUE THREAD

**Issue by Stony2k** [helios-ag/FMElfinderBundle#120]
Sorry but i have found another problem. I can't create a folder over S3. The Folder is generated on S3 but the you can't see it in the ElFinder tree. You can see the arrow before "/" but if you try to expand the tree i don't get any folders. 

Some small problems but perhaps we can fix that problems :) 

It is possible that is my mistake and i have to configure something in another way.

**Comment by helios-ag** [comment]
Well u are using Flysystem driver, there is also an elfinder driver for s3 (working directly, without flysystem), may be you should check it [too](https://github.com/helios-ag/ElFinderPHP/blob/master/src/Driver/ElFinderVolumeS3.php)?

**Comment by Stony2k** [comment]
I can try it. I have used that before but i was not working and then i changed to flysystem but i can test it again. :) thx for your fast reply.

**Comment by helios-ag** [comment]
Unfortunately i don't use S3 so can't help you much with that. Most users use only local driver.

**Comment by Stony2k** [comment]
Yes but its very important for us because the file are stored there. Do you know how to configure the native driver? There is not example in the docs. 

I have found the "s3_settings" in the config but i its not working. 

            connector:
                debug: false
                roots:
                    aws_s3:
                        driver: S3
                        url: %aws.cdn.content.url%
                        s3_settings:
                            key: %aws.key%
                            secret: %aws.secret%
                            region: %aws.region%
                            bucket_name: %aws.cdn.content.bucket%
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']

**Comment by Stony2k** [comment]
I have tried it something like this:

                roots:
                    aws_s3:
                        driver: S3
                        url: %aws.cdn.content.url%
                        s3_settings:
                            accesskey: %aws.key%
                            secretkey: %aws.secret%
                            bucket: %aws.cdn.content.bucket%
                            tmpPath: /tmp
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']

and i get an PHP error.

Compile Error: Declaration of FM\ElFinderPHP\Driver\ElFinderVolumeS3::_save() must be compatible with FM\ElFinderPHP\Driver\ElFinderVolumeDriver::_save($fp, $dir, $name, $stat)

**Comment by helios-ag** [comment]
I didn't updated this driver for a while, can you check it with latest nao-pon version, located here: https://github.com/nao-pon/elFinder/blob/2.1_n/php/elFinderVolumeS3.class.php

**Comment by Stony2k** [comment]
Same problem i have copied the complete content and replace the namespace. Same error.

**Comment by Stony2k** [comment]
Hmm i have changed the "__save" function and removed the one parameter but now i have no PHP instead he tell me that there no readable ressources :(

**Comment by Stony2k** [comment]
Another thing is that:
```
Attempted to load class "SoapClient" from namespace "FM\ElFinderPHP\Driver".
Did you forget a "use" statement for another namespace?
```
The namespace for the SOAP_Client is wrong the "\" is missing or a use statement.

**Comment by Stony2k** [comment]
Perhaps its better if i mount the folder in my filesystem and use then the local version.

**Comment by helios-ag** [comment]
Looks like the "native" elfinder S3 driver is old. Btw i worked with dropbox driver and it also have restrictions in use.

**Comment by Stony2k** [comment]
Yes its not working very well. Now i have used the s3fs driver and mapped the S3 bucket to a folder. Now i have the problem that i have set the URL and the thumbs are missing now i have to validate that.
