### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by mrcmorales** [helios-ag/FMElfinderBundle#125]
Hi,

I have this configuration:

   connector:
                debug: true # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        showhidden:     false # defaults to false
                        driver:         LocalFileSystem
                        path:           uploads/finder
                        upload_allow:   [ 'image/png', 'image/jpg', 'image/jpeg' ]
                        upload_deny:    [ 'all' ]
                        upload_max_size:  2M

The problem is that driver is not generated correct, when I select the image, in ckeditor the path is finder/... and not uploads/finder...

Thanks

**Comment by helios-ag** [comment]
Hi @mrcmorales,
well js part of elfinder don't know about of upper levels of path (more detailed explained in #116 )
in your case you can override URL option that will point to right URL root path.

**Comment by mrcmorales** [comment]
ok thanks!
