### ISSUE TITLE
Plugin ??

### ISSUE THREAD

**Issue by Snowbaha** [helios-ag/FMElfinderBundle#127]
Hello,

Elfinder 5 is working but when I added the lines for  the plugins like the example with AutoResize, I have a problem...

<pre>
Unrecognized options "bind, plugin" under "fm_elfinder.instances.ck_admin.connector"
</pre>

I didn't understand why !

My whole config : 

<pre>
fm_elfinder:
    instances:
        ck_admin:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            #relative_path: true
            connector:
                debug: true # defaults to false
                bind:
                    upload.presave:
                        - Plugin.AutoResize.onUpLoadPreSave
                plugin:
                    AutoResize: # global resize options, applies to root which don't have his own resize configuraion 
                        enable: true 
                        maxWidth: 800 
                        maxHeight: 800 
                        quality: 95 # JPEG image save quality
                        
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 5M 
</pre>

**Comment by gaet** [comment]
The same for me.

I work with the dev-master branch, all worked fine but since the last update of the bundle the "plugin" option in "connector" is unrecognized.

I think is a bug, or maybe the configuration have change.

**Comment by julinoneto** [comment]
Same for me. Since the last update

**Comment by gaet** [comment]
You can work with the 4.0.2 version, for me all works fine.

In composer.json of symfony2:
"helios-ag/fm-elfinder-bundle": "4.0.2"

**Comment by helios-ag** [comment]
Hi guys, because it tagged as 5th version, is out, and because this is a major release, there are changes in api, and configuration as well. So bind and plugin nodes was renamed to binds and plugins.

**Comment by Snowbaha** [comment]
Ok thank you, it's working ^^

**Comment by helios-ag** [comment]
Ok, closing this issue, also updated readme file, which reflect changes.
