### ISSUE TITLE
can't access to assets JS and CSS

### ISSUE THREAD

**Issue by ahmedwafdi** [helios-ag/FMElfinderBundle#129]
I installed and configured the bundle successfully. but when I load 
http://<Mysite>/app_dev.php/elfinder
nothing appears just a blank page

![selection_075](https://cloud.githubusercontent.com/assets/7659573/6881608/db71de24-d55d-11e4-991a-7f571fc257e9.png)

**Comment by nicolasmure** [comment]
Have you added this line in the `"config"` node of your composer.json ?
`"component-dir": "web/assets"`

**Comment by helios-ag** [comment]
Hi @ahmedwafdi , if you are using latest version of elfinder bundle, u need to define component-dir, that directive will tell composer to copy assets to that directory, otherwise use ~4 version of the bundle.

**Comment by ahmedwafdi** [comment]
yes i'm using the latest version , i also define component-dir in the composer.json but the same problem i dont know why but i have a question there is a difference between the the version 4 and the latest version

**Comment by helios-ag** [comment]
Do you have assets directory under web directory (and btw, is it your web-root directory)?
And answering your question about difference between 4 and 5 versions: there are not so big changes, but it will require you to update your yaml config files (sorry, i didn't update readme yet, to reflect latest changes, shortly, you need to rename bind and plugin node to binds and plugins, accordingly) and other important change is: all js and css components moved under elfinder-component repo, so this repo doesn't have any assets, only php, xml, and yml files.

**Comment by ahmedwafdi** [comment]
yes i have assets directory under web (web-root directory)

**Comment by ahmedwafdi** [comment]
![selection_078](https://cloud.githubusercontent.com/assets/7659573/7007422/bfcdb082-dc81-11e4-8c5d-82126d695e2c.png)

**Comment by helios-ag** [comment]
That's weird, looks like assets available, but ElFinder can't access them. Btw you can use version ~4. There is not much difference there.
