### ISSUE TITLE
php 5.4 syntax used (symfony2 and the bundle itself state minimum requirement to >= php 5.3.3)

### ISSUE THREAD

**Issue by bitladen-nw** [helios-ag/FMElfinderBundle#130]
Hi,

this is my first post - so if there is anything to complain about the way I am opening this issue: 
feel free to let me know... 

The subject almost says it all. I used composer to require the latest stable version, my PHP version is 5.3.10 and symfony 2.6 requires >= php5.3.3. Shouldn't this bundle be compatible with this version, too? Or did I get something wrong?

an exception is thrown in [...]/Configuration/ElFinderConfigurationReader.php at line 184 when trying to parse the short cut syntax of arrays.

symfony's and helios-ag's composer.json:
{
[...]
    "require": {
        "php": ">=5.3.3",
[...]

**Comment by helios-ag** [comment]
Hi @bitladen-nw, indeed ElFinderConfigurationReader class, use short array syntax, that can be rolled back, but ElFinderPHP library use Flysystem driver as one of the volume driver, that depends on flysystem which require php 5.4.

**Comment by bitladen-nw** [comment]
thanks for your reply. are there any chances that requiring php 5.4 will be rolled back for non-flysystem-users? would be great for not having to modify vendor files..

**Comment by helios-ag** [comment]
Ok, ill patch Reader class.

**Comment by bitladen-nw** [comment]
Thx a lot!
