### ISSUE TITLE
Dynamic path depending on the user ?

### ISSUE THREAD

**Issue by ahmedwafdi** [helios-ag/FMElfinderBundle#138]
hello World i want to overide configuration class to define a dynamique path and permision depending on the user Roles .
Please give me indications to configure FMElfinderBundle , Step by step

**Comment by helios-ag** [comment]
I've already explained it in #100.

**Comment by ahmedwafdi** [comment]
yes i know but i have somme errors like " Invalid backend configuration.
Readable volumes not available " 

this is my configuration  ( config.yml ) :

services:
    my_elfinder_configurator:
        class:  Ged\GedBundle\Controller\MyElfinderConfigurator    

fm_elfinder:
    configuration_provider: my_elfinder_configurator
    instances:
        default:
            locale: en 
            editor: ckeditor 
            fullscreen: false 
            theme: smoothness 
            include_assets: true
            connector:
                debug: true 
                roots:       
                    uploads:
                        show_hidden: false 
                        driver: LocalFileSystem
                        path: Gestion_électronique_des_documents
                        upload_allow: ['all']
                        upload_deny: ['all']
                        upload_max_size: 2M


and in the controller : 

class MyElfinderConfigurator implements ElFinderConfigurationProviderInterface {
 public function getConfiguration($instance) {
        ///some code here 
        return $options; //what i should return in $option , i wnat to dynamically change the path and keep the others configuratons 
    }
}

thank you @helios-ag

**Comment by helios-ag** [comment]
Well, i think it's better to extend ElFinderConfigurationReader (as a first approach), override constructor so it can get security context (so you can get currently logged user), inject required services:
```yml
services:
    my_elfinder_configurator:
        class: Ged\GedBundle\Controller\MyElfinderConfigurator 
        arguments: ["fm_elfinder", "@request_stack", "@service_container" , "@security_context"]
```
And override getConfiguration() method

**Comment by ahmedwafdi** [comment]
well I'm upset, what class should I extend "ElFinder Reader Configuration" or "ElFinderConfigurationProviderInterface" ?

**Comment by helios-ag** [comment]
Well it's all on to you, simple way - extend ElFinderConfigurationReader, or write own class with implemented interface.

**Comment by ahmedwafdi** [comment]
thank you, I'll extend ElFinder Configuration Reader if it is the simplest method. but I have a question in the file (config.yml) I'll keep the same configuration or not.

**Comment by helios-ag** [comment]
Yes, you need to keep yaml configuration as well.

**Comment by helios-ag** [comment]
I've blogged some instructions how to implement this functionality http://blog.fretmusic.ru/entry/how-to-implement-user-based-folders-with-fmelfinderbundle-and-fosuserbundle hope it helps to everyone who will face the same problem

**Comment by nicolasmure** [comment]
:+1: nice one @helios-ag :wink:

**Comment by xorgxx** [comment]
Hi, i wanted to see your link abort Elfinderbnudle and fosuserbundle but it down! can you give it back?

i have to find the way to provide folder spécifique for each user. i dont know are to start ?

Thank

**Comment by helios-ag** [comment]
hi @xorgxx, you can look into this https://github.com/helios-ag/elfinder-userbundle-example

**Comment by pierreboissinot** [comment]
> Well, i think it's better to extend ElFinderConfigurationReader (as a first approach), override constructor so it can get security context (so you can get currently logged user), inject required services:
> 
> ```yaml
> services:
>     my_elfinder_configurator:
>         class: Ged\GedBundle\Controller\MyElfinderConfigurator 
>         arguments: ["fm_elfinder", "@request_stack", "@service_container" , "@security_context"]
> ```
> 
> And override getConfiguration() method

Just notice `"` was forgot:
```yaml
     my_elfinder_configurator:
         class: Ged\GedBundle\Controller\MyElfinderConfigurator 
         arguments: ["%fm_elfinder%", "@request_stack", "@service_container" , "@security_context"]
```
