### ISSUE TITLE
Disallow creating/uploading new folder

### ISSUE THREAD

**Issue by TisLars** [helios-ag/FMElfinderBundle#139]
Hello,

How would I disable the option to create/drag a new folder in the ElFinder page? I only want the user to upload images.

Thanks in advance,

Lars

**Comment by helios-ag** [comment]
Look at issue #74, note that node has been renamed from disabled to disabled_commands, set it to  [mkdir]

**Comment by TisLars** [comment]
Thanks for the quick response!
This worked perfectly and it's a real helpfull bundle.
