### ISSUE TITLE
Uncaught TypeError: a.indexOf is not a function (IvoryCkEditor Insert Image)

### ISSUE THREAD

**Issue by ppounder** [helios-ag/FMElfinderBundle#144]
Hi there,

I'm trying to integrate FMElfinderBundle into IvoryCkEditorBundle.

I'm using:
Symfony 2.6.4. 
IvoryCkEditorBundle: 3.0.x
FMElfinderBundle: 4.0.2 (I have tried with 5.0.4 and the same occurs)
jQuery 1.11

I am configuring the CkEditor on the Form Type:
```
->add('content', 'ckeditor', array(
                'label' => 'Email Content',
                'required'  => true,
                'config' => array(
                    'filebrowserImageUploadUrl' => array(
                        'route'            => 'elfinder',
                        'route_parameters' => array(
                            'instance' => 'default'
                        ),
                    ),
                ),

            ))
```
config.yml
```
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 8M
```

And I am getting the following when I click the Insert Image icon on the editor:
```
Uncaught TypeError: a.indexOf is not a function
g @ ckeditor.js:716
m @ ckeditor.js:718
j @ ckeditor.js:719
(anonymous function) @ ckeditor.js:721
j @ ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.dialog @ ckeditor.js:529
CKEDITOR.tools.extend.openDialog @ ckeditor.js:574
(anonymous function) @ ckeditor.js:575
CKEDITOR.scriptLoader.load.m @ ckeditor.js:221
CKEDITOR.scriptLoader.load.y @ ckeditor.js:221
CKEDITOR.scriptLoader.load.s @ ckeditor.js:221
(anonymous function) @ ckeditor.js:222
```

![fmelfinder](https://cloud.githubusercontent.com/assets/343006/7510806/e18c9124-f497-11e4-8014-3e260b613d3d.png)

Looking at the compressed ckeditor.js file it seems to be around an issue with the following ```function:CKEDITOR.tools.extend(CKEDITOR.editor.prototype,{popup:function(e,a,b,d)...```

I have tried my setup on a simple form field upload (not ckeditor) and this works. It only seems to be an issue with CkEditor (obviously...with the issue linking to the ckeditor.js)

It seems to be around this area here:
```return a+(-1!=a.indexOf("?")?"&":"?")+d.join("&")}```

Not sure what ```a``` should be in this function

**Comment by helios-ag** [comment]
Hi @ppounder, sorry for late answer,
I reproduced your behavior, and found that you need to modify form builder as follows:
```php 
->add('content', 'ckeditor', array(
    'label' => 'Email Content',
    'required'  => true,
    'config' => array(
        'filebrowserBrowseRoute' => 'elfinder',
        'filebrowserBrowseRouteParameters' => array('instance' => 'default')
        )
    )
)
```

**Comment by ppounder** [comment]
That's great, yes that worked for me. 

Many thanks
Paul

**Comment by saran110313** [comment]
how to solve this method error Uncaught TypeError: url.indexOf is not a function(png images)

**Comment by helios-ag** [comment]
Hi @saran110313, please share more information about your issue.

**Comment by saran110313** [comment]
hi,
  canvas.add(new fabric.Image.url.indexof(circ));
This code error in
Uncaught TypeError: Cannot read property 'getActiveObject' of undefined..

**Comment by saran110313** [comment]
hi,
  how to add image add and modify function in fabricjs......

**Comment by helios-ag** [comment]
Actually i don't understand how this related to FMElinderBundle. It's written in php for symfony.

**Comment by saran110313** [comment]
hi,
  i working in html5 and node java script projects..

**Comment by helios-ag** [comment]
Still doesn't make sense for me, please post your question to StackOverflow.

**Comment by saran110313** [comment]
ok thank you
