### ISSUE TITLE
GridFs support ? (Flysystem / Gaufrette)

### ISSUE THREAD

**Issue by yaK2manD** [helios-ag/FMElfinderBundle#145]
Hi,

I would like to get FMElfinderBundle working with GridFs. I tried several solutions such as Flysystem  or gaufrette throught an alternative solution.

Do you have an idea who to proceed in order to get GridFs with FMElfinderBundle ?

Thank you

**Comment by helios-ag** [comment]
Hi @yaK2manD,
what do you mean under 'alternate' solution?
Have you tried flysystem/gridfs driver (actually i didn't worked with it at all)?

**Comment by helios-ag** [comment]
ping @yaK2manD
