### ISSUE TITLE
Unable to connect to the backend.

### ISSUE THREAD

**Issue by internoleduc** [helios-ag/FMElfinderBundle#149]
Hello 

I have create a new configuration file and extend from default FMElfinderBundle Configurator and i'm unable to connect to the backend. When using the default configuration of FMELfinderBundle, there's no errors. 
How to properly change the default configuration ?
![backend](https://cloud.githubusercontent.com/assets/5027132/7939163/0e0ae95c-0939-11e5-93bb-2a58a9704423.PNG)

Thank you @helios-ag

**Comment by helios-ag** [comment]
I need more details, how did you extend configuration? Have your registered your class as service and etc.

**Comment by internoleduc** [comment]
Hello  @helios-ag,

Thank you for your reply but I just deal with this, it was a bad statement of the argument fm_elfinder in service .... In fact I would like to manage multiple rights over a file from one directory to several different users. The name and file path are persisted in the database and users with access rights to each file as well. In summary, the same file will be hidden for certain users and visible for others. Could you enlighten me and guided me, I'm a little lost here.

**Comment by helios-ag** [comment]
Well as you already know, you can extend ElFinderConfigurationReader class, and you need to override methods getConfiguration(), or access() (or both, depends on implementation).
Also you will need to inject "security.context" service your new elfinder configuration service. 
The next step is rewriting access($attr, $path, $data, $volume) method, you need to compare users attributes, that contain filenames (btw i don't think that storing filenames is a efficient way, better to store directories, that user have access rights) and current $path, and return true/false.

**Comment by internoleduc** [comment]
Thanks,

That's was the problem... I had to make directories control than filename. Thanks
