### ISSUE TITLE
Path error with nested folders (uploads/bob)

### ISSUE THREAD

**Issue by gittix09** [helios-ag/FMElfinderBundle#152]
Issue #116 shoud be reopened
I also encountered this problem. More details here:
https://github.com/helios-ag/FMElfinderBundle/issues/116#issuecomment-115691217

Is there a solution or will there be one in the near future?

**Comment by picks44** [comment]
Same problem here, fixed with "relative_path" config set to "false" but could be good to have a fix with relative paths allowed...

**Comment by helios-ag** [comment]
Some improvements made in 1292ed209a779cd3de87a31fbafea5965c5f646a, you could check latest version of the bundle.
