### ISSUE TITLE
Why this bundle generates Symfony2 doctrine migration file?

### ISSUE THREAD

**Issue by cithukyaw** [helios-ag/FMElfinderBundle#157]
I'm using this bundle in my Symfony2 application. When I run `php app/console doctrine:migrations:diff` , I got a new migration file

    /**
     * Auto-generated Migration: Please modify to your needs!
     */
    class Version20150804105019 extends AbstractMigration
    {
        /**
         * @param Schema $schema
         */
        public function up(Schema $schema)
        {
            // this up() migration is auto-generated, please modify it to your needs
            $this->abortIf(
                $this->connection->getDatabasePlatform()->getName() != 'mysql',
                'Migration can only be executed safely on \'mysql\'.'
            );

            $this->addSql('CREATE TABLE elfinder_file (
                id INT AUTO_INCREMENT NOT NULL,
                parent_id INT NOT NULL,
                name VARCHAR(255) NOT NULL,
                content LONGBLOB NOT NULL,
                size INT NOT NULL,
                mtime INT NOT NULL,
                mime VARCHAR(255) NOT NULL,
                `read` VARCHAR(255) NOT NULL,
                `write` VARCHAR(255) NOT NULL,
                locked VARCHAR(255) NOT NULL,
                hidden VARCHAR(255) NOT NULL,
                width INT NOT NULL, height INT NOT NULL,
                INDEX parent_id (parent_id),
                UNIQUE INDEX parent_name (parent_id, name),
                PRIMARY KEY(id)
            ) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        }

        /**
         * @param Schema $schema
         */
        public function down(Schema $schema)
        {
            // this down() migration is auto-generated, please modify it to your needs
            $this->abortIf(
                $this->connection->getDatabasePlatform()->getName() != 'mysql',
                'Migration can only be executed safely on \'mysql\'.'
            );

            $this->addSql('DROP TABLE elfinder_file');
        }
    }

I did not notice that it needs a table. I just noticed it lately when I generated the migration file for the other module update in my application.

I'm just using this to upload images in [IvoryCKEditor](https://github.com/egeloen/IvoryCKEditorBundle). It is working fine without that table. Why and when the table is needed?

**Comment by helios-ag** [comment]
Hi @cithukyaw, that table required for mysql driver of elfinder (the bundle ships with entity for it). Mysql driver stores file infortmation in sql table.

**Comment by helios-ag** [comment]
moved doctrine migration file to resource folder f48020eb7f0eba40b242e80c36798be46fd64a0e
