### ISSUE TITLE
FMElfinderBundle shows nothing

### ISSUE THREAD

**Issue by elenitaex5** [helios-ag/FMElfinderBundle#159]
Hi, 
I'm trying to use FMElfinderBundle with TrsteelCkEditor.

This is my config.yml with the finish of TrsteelCKeditor configuration and all of FMElfinder configuration

![image](https://cloud.githubusercontent.com/assets/14013852/9567025/2ed0da6a-4f1c-11e5-86d8-bba24225d7fd.png)

When I push Image button in CKEditor it opens 'Image properties' and when I try to 'View Server' in 'Image Information' it only opens a white windows, without nothing at all. Symfony give me a 200 so there's no error server and if I write something in 'ckeditor.html.twig' appears in the window. So seems the js doesn't work fine. Maybe cause of my configuration...

Could anybody helps me?

**Comment by helios-ag** [comment]
Which version do you use?
Do you have elfinder assets in web/assets folder under public root?
If it is latest version, have you defined component-dir in composer.json?

**Comment by elenitaex5** [comment]
I'm using 5.0 version and I've defined the component-dir in my composer.json
![image](https://cloud.githubusercontent.com/assets/14013852/9573128/ce314abc-4fb8-11e5-95c1-719972b4eaac.png)

In fact el finder creates the folder.
![image](https://cloud.githubusercontent.com/assets/14013852/9573144/0b20d46a-4fb9-11e5-8845-6b72d9721615.png)

before trying to use this bundle I had another folder three:

web > bundles > MyBundle > images

maybe I have to copy everything in 'assets' folder and change paths?

**Comment by helios-ag** [comment]
Looks fine, can you check assets network requests under developer console(firebug) in firefox/chrome? May be elfinder tries to load assets from different resources, as we expected.

**Comment by mbo2olivier** [comment]
Hi all,
i have exactly the same problems, and my configuration is similar to this one. when i try to check network request with FireFox developpers tools, as expected, eLfinder try to load resources from my WAMP root (http://localhost/assets/jquery...).
there is no way to manually set assets path in Elfinder?
PS: my english is probably full of mistakes, please be indulgent, i'm not form an english speakin country.

**Comment by wassimjahid** [comment]
Hello everybody,
I have the same problem as @elenitaex5 and @mbo2olivier 
I put a print screen of the console.
![elfinder problem](https://cloud.githubusercontent.com/assets/11244501/9625312/064caf46-514d-11e5-8514-03df4ce746fd.jpg)
Any ideas please?

**Comment by helios-ag** [comment]
Hi @elenitaex5, @mbo2olivier, @wassimjahid.
Thank you @wassimjahid for sharing screenshot.
You can set 'assets_path' option under fm_elfinder node
```yaml
fm_elfinder:
    assets_path: /assets # default is '/assets', you can replace it with '/awb/web/assets' in you case
    instances:
        default:
            locale: %locale% # 
...
```

**Comment by wassimjahid** [comment]
THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU 
You saved my life it works perfectly :D

**Comment by helios-ag** [comment]
Btw i highly recommend to setup your dev environment with virtual hosts (or at least use php built-in web server).

**Comment by wassimjahid** [comment]
How can I do that? some advise plz...

**Comment by helios-ag** [comment]
If you work under windows, look at this: http://stackoverflow.com/questions/2658173/setup-apache-virtualhost-windows

**Comment by nicolasmure** [comment]
Php built in web server : 
- http://php.net/manual/en/features.commandline.webserver.php
- http://symfony.com/doc/current/cookbook/web_server/built_in.html

Apache2 virtual hosts:
- https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts

In web development you'll find the majority of help and tutos for unix computers, so I highly recommend you to use linux. If you want to keep your windows machine, you can set-up a docker environment on windows host running a linux image : https://docs.docker.com/installation/windows/

**Comment by wassimjahid** [comment]
Thank u all, I'll take a look at this

**Comment by elenitaex5** [comment]
Thank you @helios-ag I've changed the assets_path and works perfectly. 
I don't know if there another question in this post but you can close it if depends of me

**Comment by mbo2olivier** [comment]
Thank you so much @helios-ag , it work perfectly! but i'have to setup a virtual host for more flexibility. thank u all.

**Comment by mbo2olivier** [comment]
Thank you so much @helios-ag , it work perfectly! but i'have to setup a virtual host for more flexibility. thank u all.

**Comment by helios-ag** [comment]
Also you can check vagrant and [puphpet](https://puphpet.com/)
@elenitaex5 if everything is working now, you can close this issue.

**Comment by mouradevsoltani** [comment]
Hi,
I have a white windows when I try to 'View Server'.
![error](https://cloud.githubusercontent.com/assets/15234497/11328121/18e9adee-9184-11e5-9c4b-5fd29431d2d0.png)

I'm using version 5.
This is my configuration
![config](https://cloud.githubusercontent.com/assets/15234497/11328201/f0a2f0e6-9185-11e5-8886-6a9f011a76d8.png)

and this my form
![formtype](https://cloud.githubusercontent.com/assets/15234497/11328235/82acbb16-9186-11e5-886c-04c99408d954.png)

Help me please

**Comment by helios-ag** [comment]
hi @mouradevsoltani, have you added 
```
{
    "config": {
        "component-dir": "web/assets"
    }
}
```
to composer.json?

**Comment by mouradevsoltani** [comment]
Hi @helios-ag , yes i added 
{
    "config": {
        "component-dir": "web/assets"
    }
}
but nothing changed !

**Comment by joelranjithjebanesan7** [comment]
@helios-ag  I have an issue, I can't configure tools through fm_elfinder configuration,I controll the elfinder tools by changing elfinder.min.js but it get reseted after composer update.How to configure tools through configuration
