### ISSUE TITLE
Bug on getUrl function with HomeFolder

### ISSUE THREAD

**Issue by Solirio** [helios-ag/FMElfinderBundle#161]
Hello everyone, (Be ready for my english, im french, so sorry if it's bad)

After hours of research on a bug inside my app, i think i found it in ElfinderBundle.

My path `uploads/img/etablissements`
My HomeFolder var can change all the time, but here is an exemple: `16/espace`

So the complete url can be `uploads/img/etablissements/16/espace`

It work well with everything exept the url of the Img. When i watch the src i see:
`uploads/img/etablissements//16/espace/myimg.jpg`

You can see a double / between my path and my homeFolder.
It make sometimes problem in TinyMce editor, img were sometimes like corrupted or not found in the editor. Most of the time it work. But i can't let bug like that even if it happen not often.

I found the problem in ElFinderConfigurationReader.

Inside the getConfiguration function. There is this code:

`if ($homeFolder !== '') {
                $homeFolder = '/'.$homeFolder.'/';
            }`

this var is used two times:
For the path of the backend in the `$driverOptions` array:
`'path'              => $path . $homeFolder`

So path will be in my case `uploads/img/etablissements/16/espace`
It's good

And for the URL of content in the `$driverOptions` too:
`'URL'               => $this->getURL($parameter, $request, $homeFolder, $path)`

The bug is inside getURL function:

`sprintf('%s://%s%s/%s/%s', $request->getScheme(), $request->getHttpHost(), $request->getBasePath(), $path, $homeFolder)`

U can see an other `/` is added between $path and $homeFolder.
But one was already added in the getConfiguration function.

It's maybe normal, maybe i don't understand everything, all i know is this double slash made somes bug on my app. 

Have Good Day guys :)

**Comment by nicolasmure** [comment]
Hi,

maybe this can help you : https://github.com/helios-ag/FMElfinderBundle/issues/158#issuecomment-136022091

**Comment by Solirio** [comment]
Hi, thank u for the answer, in my case it doest not solve my problem, i will probably just rewrite the getURL function.

The double "/" is not before the path, but between path and homefolder. I tryied ur solution, but not working.

**Comment by helios-ag** [comment]
Hi @Solirio, what is your dev platform (win/linux/macos)?

**Comment by Solirio** [comment]
The problem appear on Windows and Linux Debian

**Comment by Invis1ble** [comment]
Hello, I have the same issue on Windows 7, not tested yet on Linux.

**Comment by Invis1ble** [comment]
In my case the bug also in extra slash between path and homeFolder in https://github.com/helios-ag/FMElfinderBundle/blob/0147ea039b8abd717186ac1502ca4356cb6ce39e/Configuration/ElFinderConfigurationReader.php#L160.
Patching this function seems solves issue.
