### ISSUE TITLE
Wrong mime type with flysystem s3 driver

### ISSUE THREAD

**Issue by hoangnd25** [helios-ag/FMElfinderBundle#164]
I'm using this bundle with flysystem for uploading file to amazon s3. However, the mime type returned is always binary/octet-stream. I'm guessing because the mime type was not set so it is defaulted to binary/octet-stream.

This problem could be similar to this:
https://github.com/barryvdh/elfinder-flysystem-driver/issues/8

**Comment by helios-ag** [comment]
Hi @hoangnd25, can you check if this change fix your issue?

**Comment by hoangnd25** [comment]
Yeah, that change fixed the problem.

**Comment by hoangnd25** [comment]
I created a pr
https://github.com/helios-ag/ElFinderPHP/pull/26

**Comment by helios-ag** [comment]
merged, tagged as 2.3.4
