### ISSUE TITLE
Encode / Decode Path

### ISSUE THREAD

**Issue by Ronan-Lenor** [helios-ag/FMElfinderBundle#169]
Hello,
as the whole interaction betwen the backend end frontend pass through the encrypted path (hash), i need to access to the endode and decode method of the class ElFinderVolumeDriver.

it could be easy to access it through the loader service.
but ElFinderLoader.php and all drivers need some modification.

do i have your green light?

**Comment by helios-ag** [comment]
Why not, but can you explain it a little bit more. 
Also we will need to care about symfony-cmf drivers too. Their driver is used for phpcr interaction.

**Comment by Ronan-Lenor** [comment]
Well, my idea is in order (to use it from the pre post event)
1: get the loader service (already possible)

2: from the loader, get the ElFinderBridge
actually, there's no way to access it. Coz it is directly instantiate in the Connector instantiation.

    $connector = new ElFinderConnector(new ElFinderBridge($config));
so i will store 1st the Bridge in a parameter.

3: now that we have the bridge, we can almost access to the encode/decode function of the class ElFinderVolumeDriver. but 1 they are protected, 2 it's an abstract class extend by all that others class:
- ElFinderVolumeDropbox
- ElFinderVolumeFileSystem
- ElFinderVolumeFTP
- ElFinderVolumeLocalFileSystem
etc...

inside those class i just need to had such function like:

    public function encode($path) {
         return parent::encode($path);
    }

Finish !
Well, i have sow it with public function from ElFinderVolumeXXXX class, but i think that i would prefer create protected function (as the bridge itself bring nothing particular) upto the ElFinderLoader.

so from the loader service we could do something like $Loader->encode('my/path');

validate?

**Comment by Ronan-Lenor** [comment]
done.
1: https://github.com/helios-ag/ElFinderPHP/pull/31
2: https://github.com/helios-ag/FMElfinderBundle/pull/170

**Comment by Ronan-Lenor** [comment]
Any news about it ? :)
i'm getting late on my project xP i'm gonna get some trouble ^^;
