### ISSUE TITLE
FMElfinderBundle shows white window

### ISSUE THREAD

**Issue by mouradevsoltani** [helios-ag/FMElfinderBundle#184]
Hi, 
I'm trying to use FMElfinderBundle with IvoryCKEditorBundle.

When I push Image button in CKEditor it opens 'Image properties' and when I try to 'View Server' in 'Image Information' it only opens a white windows, without nothing at all.

![error](https://cloud.githubusercontent.com/assets/15234497/11328338/aa7f6092-9188-11e5-9dd1-093ec5e61718.png)

I'm using 5.0 version and I've defined the component-dir in my composer.json
I set  assets_path: /assets but nothing  changed !

this is my configuration:
![config](https://cloud.githubusercontent.com/assets/15234497/11328315/41494a0c-9188-11e5-84fa-7d7b60416eed.png)

and this is my FormType:
![formtype](https://cloud.githubusercontent.com/assets/15234497/11328322/68034184-9188-11e5-908d-c27404e0e3a0.png)
 
Could anybody helps me?

**Comment by helios-ag** [comment]
I answered you in #159, also check developer console in your web browser, maybe you will need to setup 'path_prefix' accordingly as you don't use vhosts.

**Comment by mouradevsoltani** [comment]
Hi @helios-ag , I don't use vhosts.
how I can use 'path_prefix' ?

**Comment by helios-ag** [comment]
Open dev console on network tab and look where templates is looking for elfinder assets. And change path_prefix accordingly. You will have to set path_prefix something like as "path_prefix: /aditus/web" (you probably to adjust this by yourself).

**Comment by mouradevsoltani** [comment]
@helios-ag thank you very much it works perfectly :)
