### ISSUE TITLE
How to dynamicly create folder ?

### ISSUE THREAD

**Issue by chadyred** [helios-ag/FMElfinderBundle#189]
Hello,

this is my conf

<pre>
fm_elfinder:
    # assets_path: /web/assets V5
    instances:
        default:
            relative_path: false #permet d'utiliser l'URL en absolute
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme V5
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            path_prefix: http://application.local:8080
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false

            relative_path: false #permet d'utiliser l'URL en absolute
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme V5
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            path_prefix: http://application.local:8080
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads/default/flo #...non chrootera dans ce dossier
                        url: uploads/default/flo #URL utilisé /elfinder/{instance}/{homeFolder}
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
</pre>

I defined in a static way here. How to defined a "homeFolder" dynamicly? In other word, "homeFolder" will be create in the instance folder, with is id. 

I just want to know if you ever try this? I think I could use this classe to redefined parameters:  

https://github.com/helios-ag/FMElfinderBundle/blob/master/Configuration/ElFinderConfigurationReader.php

**Comment by helios-ag** [comment]
Hi @chadyred, you can override ElFinderConfigurationReader class with your own, more information can be found [here](https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/doc/advanced-configuration.md#custom-configuration-provider)
