### ISSUE TITLE
Symfony 3.0

### ISSUE THREAD

**Issue by HarryWiseman** [helios-ag/FMElfinderBundle#190]
Hi,

Just wondering if you were intending on updating the bundle to work with symfony 3.0?

Thanks,

Harry

**Comment by helios-ag** [comment]
Hi @HarryWiseman, the master should work with 3.0, i have updated it recently. Didn't tag it yet.

**Comment by helios-ag** [comment]
Tagged as 6.0, https://github.com/helios-ag/FMElfinderBundle/releases/tag/6.0
