### ISSUE TITLE
How to show only certain mime types from configuration?

### ISSUE THREAD

**Issue by jstnthms** [helios-ag/FMElfinderBundle#193]
I see there is an option to [set the visible mime types from the client side](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#onlyMimes), and I know I can restrict the uploadable mime types from the configuration, but I don't see how I can set the visible mime types from configuration.

Is overriding the ElFinder Controller and templates my only option right now?

--

Assuming there is no way to set the visible mime types through the configuration, it would be nice to be able to do something like this:

    fm_elfinder:
        instances:
            default:
                # ...
                connector:
                    # ...
                    roots:
                        uploads:
                            # ...
                            upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                            visible_mime_types: [] # defaults to value of upload_allow

then ElFinderController would pass along a template variable called `mimeTypes`, set to the value of `visible_mime_types`.

    $('.elfinder').elfinder({
        // ...
        mimeTypes: mimeTypes,
        // ...
    });

It would be a whole lot cleaner than having to override the controller and several templates. Plus, if you are restricting the uploadable types, you probably want to restrict the visible types the same way. Specifically, for inserting images into a wysiwyg, or if you have a file select field for PDFs only, etc.

**Comment by helios-ag** [comment]
Hi @jstnthms, do you willing to make PR?

**Comment by jstnthms** [comment]
Ya, I can do that since I will be doing the work for my project anyways.

**Comment by helios-ag** [comment]
Why not, i will accept it :+1:

**Comment by jstnthms** [comment]
For continuity, pull request is here: https://github.com/helios-ag/FMElfinderBundle/pull/195

**Comment by helios-ag** [comment]
merged and tagged as 6.0.1
