### ISSUE TITLE
Usage of "elfinder" Form Type in version "~6"

### ISSUE THREAD

**Issue by jstnthms** [helios-ag/FMElfinderBundle#196]
Symfony gives the error `Could not load type "elfinder"` because the service is no longer associated with that alias. Version "~6" of your bundle says "Symfony 3 compatible", but it seems to be able to get away with 2.8.

Could you add something to the docs about what minimum versions of Symfony are supported by certain versions of the bundle? And possibly something about how to use the "elfinder" type in version "~6" of the bundle?

```
// ...
use FM\ElfinderBundle\Form\Type\ElFinderType;
// ...
$builder->add('elfinder', ElFinderType::class); // instead of type 'elfinder'
```

**Comment by helios-ag** [comment]
I'm working on v6 to be backward compatible with earlier versions.
