### ISSUE TITLE
Full absolute path to image

### ISSUE THREAD

**Issue by ppounder** [helios-ag/FMElfinderBundle#199]
Hi there,

Absolutely love the bundle. I'm using this with KNP Snappy Bundle to output some of my content to PDF. This requires the uploaded images to have full absolute path to the image location.

Can you advise how I can prefix my base url to the image location so that when an image is selected it shows the full path not just the path from the webroot.

Example:
I require the path to the image to be: http://localhost/uploads/image.png, at the moment I have it as: /uploads/image.png

This is currently my config:
````
roots:       # at least one root must be defined
    uploads:
        show_hidden: false # defaults to false
        driver: LocalFileSystem
        path: uploads
        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
        upload_deny: ['all']
        upload_max_size: 128M
````
I've tried adding the `url: "http://localhost/uploads"` and `url: "http://localhost/"` to the config, but that isn't doing anything, or I'm using it incorrectly. Any help would be appreciated.

Kindest regards
Paul

**Comment by helios-ag** [comment]
Hi @ppounder, you can set "relative_path" option to false, under your instance node, i.e.
```yaml
fm_elfinder:
   instances:
       default:
           relative_path: false #default true
...
```
There is also 'path_prefix' option, which you can adjust, if you have your project that isn't configured as vhost (i.e. 127.0.0.1/symfony_project/web/app_dev.php).

**Comment by ppounder** [comment]
As simple as that, many thanks :-) :+1:
