### ISSUE TITLE
Used "helios-ag/fm-elfinder-bundle": "~6" shows nothing

### ISSUE THREAD

**Issue by zhaocunyang** [helios-ag/FMElfinderBundle#202]
used symfony 3.0 so i use helios-ag/fm-elfinder-bundle ~6
my config is
![940f1b5c-1283-4f1f-93ee-7c8513dd74be](https://cloud.githubusercontent.com/assets/10735017/11838592/03884152-a423-11e5-8266-c35ea1637019.png)

then i assis:install prompt nothing install i see fm-elfinder-bundle Resources not found public folder,so Page not being given, but always nothing,

Could anybody helps me?

**Comment by helios-ag** [comment]
Have you added 
```json
{
    "config": {
        "component-dir": "web/assets"
    }
}
```
to composer.json?
is web/assets folder is populated by assets (elfinder css/js) files?

**Comment by zhaocunyang** [comment]
thanks it work!!
