### ISSUE TITLE
config Elfinder Form Type have problem

### ISSUE THREAD

**Issue by zhaocunyang** [helios-ag/FMElfinderBundle#204]
i config is 
![image](https://cloud.githubusercontent.com/assets/10735017/11890836/b960256e-a593-11e5-9661-2d8dc74c5041.png)
![image](https://cloud.githubusercontent.com/assets/10735017/11890847/d28aa1d6-a593-11e5-943b-88d8d32aa283.png)
jquery is jquery-2.1.4 
$ is not defined
![image](https://cloud.githubusercontent.com/assets/10735017/11890866/026f5770-a594-11e5-9470-e2b39843ea80.png)
Could anybody helps me?

**Comment by zhaocunyang** [comment]
The problem is solved

**Comment by helios-ag** [comment]
I like how this issues are solved :blush:
