### ISSUE TITLE
Issue for custom service driver (with solution)

### ISSUE THREAD

**Issue by hen-sen** [helios-ag/FMElfinderBundle#205]
In th Bridge/ElFinderBridge.php, line 25 : the variable $driver is assigned to the variable $volume.
But in PHP the object assignments are done by reference. 
So in that case, all the previous $volume variables are modifies on each loop !
Replacing `$volume = $driver;` by `$volume = clone($driver);` solve the issue :)

**Comment by helios-ag** [comment]
What kind of custom volume driver have you used, if it isn't a secret of course (guess CMF)?

**Comment by sauliwx** [comment]
Hi :) 
It's not for a CMF more for a media library.
So I have overrided some of the ElFinderVolumeLocalFileSystem' functions (mkfile, copy, move ...) to add a record in my database for each files in my media upload folder, basically with an id and a path.

**Comment by helios-ag** [comment]
If your driver isn't strictly specific to your project, you can contribute it to ElFinderPHP repository, so it can become core driver, and can be used by other bundle users.

**Comment by sauliwx** [comment]
It is a bit specific because it use a custom doctrine entity. But I can still share it for improvement purpose.
I just don't know how ...

**Comment by helios-ag** [comment]
You can share solution via repository wiki.
