### ISSUE TITLE
How can get url that selected Image?

### ISSUE THREAD

**Issue by helloooideeeeea** [helios-ag/FMElfinderBundle#209]
I want to get url that selected image like the following's kcfinder's demo.
http://kcfinder.sunhater.com/demos/image

How do i implement?
thanks.

**Comment by sauliwx** [comment]
You can get it with the `url(hash)` and `selected()` functions..
For instance : `var url = elFinder.url(elFinder.selected());`

A whole exemple :

    var $f = $('.elfinder').elfinder({ 
        ... 
        handlers : {
            select : function(event, instance) {
                watever.you.want.with getSelectedUrls();
            }
        }
    });

    var elFinder = $f.getElFinder();
    
    function getSelectedUrls() {
        var selectedUrls = [];
        var selectedHashs = elFinder.selected();
        for (var key in selectedHashs) {
            selectedUrls.push(elFinder.url(selectedHashs[key]));
        }
        return selectedUrls;
    }

**Comment by helios-ag** [comment]
Also you can look at [widget](https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/views/Form/elfinder_widget.html.twig) and  [form_type](https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/views/Elfinder/elfinder_type.html.twig) as a example

**Comment by helloooideeeeea** [comment]
@helios-ag @sauliwx thanks! I read widget and form_type 's link. and I understood.
 
I wrote the following's code. 

public function buildForm(FormBuilderInterface $builder, array $options) {
$builder
....
->add('thumbnail', ElFinderType::class, array(
'label' => 'icon_catch',
'required' => true,
'enable' => true,
'instance' => 'my_form',
'attr' => [
   'class' => 'form-control'
]))

thanks.
