### ISSUE TITLE
No callback sync to form field

### ISSUE THREAD

**Issue by swinter** [helios-ag/FMElfinderBundle#212]
I use Elfinder version 6 together with Symfony 2.9. When I open Elfinder via the Form-Method the Elfinder browser window will not close on double click on any item. Also the form field will not be updated. I also integrated Elfinder with IvoryCKEditorBundle in the same project. That solution is working.

**Comment by helios-ag** [comment]
Hi @swinter, you need to include jquery, on page where you have placed elfinder form.

**Comment by swinter** [comment]
Dear Al,
jquery is included bevor the javascript code from the form. The 
javascript code to brin up the ELfinder Window is working. Elfinder 
pops-up. I can browser the direcoties and can do some work with the 
images. But if I want to select an image with double click, the Elfinder 
browser window gives not the new filename back to the symfony form field.

This is my form field:

->add('fileName', ElFinderType::class, array('instance'=>'form', 
'enable'=>true)) ->add('text', CKEditorType::class, array( 'config' => 
array( 'filebrowserBrowseRoute' => 'elfinder', 
'filebrowserBrowseRouteParameters' => array('instance' => 'default'), ) ))

CkEditor combined with ElFinder is working correctly. But the first form 
field ist the problem.

Thanks in advance
Stephan




Am 12.01.2016 um 15:44 schrieb Al Ganiev:

**Comment by swinter** [comment]
Dear Al,
I made a screenshot. For example the file "img1.png" will not been taken 
over to the form field FileName from where the Finder window was opened.

Best regards
Stephan






Am 12.01.2016 um 15:44 schrieb Al Ganiev:

**Comment by helios-ag** [comment]
Hi Stephan, unfortunately github can't transfer images through emails, so they should be attached via github issue tracker.
Related to your issue, can you open developer console (i.e. firebug) and check js error messages there?

**Comment by swinter** [comment]
Hi Al,
now I understand github. I have appended the image. Where can I see the error messages in Firebug?

![clipboard01](https://cloud.githubusercontent.com/assets/17857/12295446/686caf9c-ba01-11e5-9eba-6135b3bf8d59.jpg)

**Comment by swinter** [comment]
I accidently closed the comment. Hope it is open again

**Comment by helios-ag** [comment]
I see that fileName form field populated, but did you populate it manually (or with ElfinderFormType)? Also can you show dev console, when you double click on file?
