### ISSUE TITLE
wrong assets path requested

### ISSUE THREAD

**Issue by hero789** [helios-ag/FMElfinderBundle#213]
hello , 
i'm using elfinder ver 6.0 with ckeditor bundles when open the upload dialog i got blank page with js errors like follow for all files  , 
`NetworkError: 404 Not Found http://localhost/assets/elfinder/dist/js/i18n/elfinder.en.js"` obviously the URL is misspelled however my app url should be for instance `/shabandar/web/public/cdn/logo.png`.
and i did added the "web/assets" and i even create the assests folder which was not exist before .
is the any configuration or routes to fix this ?

**Comment by hero789** [comment]
hereis my configuration 
    m_elfinder:
    instances:
        default:
            relative_path: false
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce,  form, simple, custom
            #editor_template: set custom template for your editor # default null
            path_prefix: '/web/assets' # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # defaults true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        #show_hidden: true|false # defaults to false, hide files that
                        driver: LocalFileSystem
                        path: /shabandar/web/assets/

                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

**Comment by nicolasmure** [comment]
Hi,

maybe `app/console assets:install` could help you ?

**Comment by helios-ag** [comment]
Hi @hero789, have you added this part to composer.json

```json
{
    "config": {
        "component-dir": "web/assets"
    }
}
```
?

**Comment by skerit** [comment]
I have the same issue, even when adding the `component-dir` to the composer.json file.

Running `app/console assets:install web` also doesn't seem to install anything for the FMElfinderBundle

**Comment by helios-ag** [comment]
Yep, assets:install dump assets that comes with bundle (and it is appliable up to version ~4), but since version 5, assets moved to their own repo and installed via component installer.

**Comment by bartolije** [comment]
Hello,

Same issue here, while openning file manager, i'm unable to load all assets (js/css)
