### ISSUE TITLE
Content of Elfinder page is not displayed

### ISSUE THREAD

**Issue by MustaphaSakka** [helios-ag/FMElfinderBundle#218]
Hello,

I have already configured Symfony2 with IvoryCKEditor and FMElfinder, following these steps https://github.com/helios-ag/FMElfinderBundle , in order to upload images from my local directory.
The problem that when I click on the **Browse Server** button, I obtain a new window with a blank page. 
I think that the elfinder page is loaded but content is not displayed.

Can someone help me to find the solution?
Thanks!

**Comment by helios-ag** [comment]
Hi @MustaphaSakka, have you added 
```json
{
    "config": {
        "component-dir": "web/assets"
    }
}
```
to composer.json?

**Comment by MustaphaSakka** [comment]
Thank you @helios-ag !

I installed the version 6 of FMEIfinder. It's weird that this instruction is mentioned only for version 5 on the  document. Anyway, it's works well now !
