### ISSUE TITLE
Custom Elfinder theme

### ISSUE THREAD

**Issue by rvmourik** [helios-ag/FMElfinderBundle#222]
Hi There,

I want to include a custom theme for elfinder, the only way to achieve this AFAIK is including your one theme.css instead of the default one Elfinder is using.

Is there a way to accomplish this with the bundle?

Thanks.

Robbert

**Comment by helios-ag** [comment]
Hi Robbert!
Looks like you have two ways achieving this, one is proposed by you, another is to override https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/views/Elfinder/helper/assets_css.html.twig change names/paths for yours theme.css

**Comment by rvmourik** [comment]
Hi,

Okay, but elfinder is loaded into an iframe (pop-up), so it would be difficult to load external scripts. Only by editing core bundle files. The same with the second way you proposing, editing core bundle files is far from ideal when wanting to update to a new version.

Isn't it possible to add a overridable option in the config for the twig files?

Thanks for your help so far.

Robbert
