### ISSUE TITLE
fm-elfinder-php-connector error

### ISSUE THREAD

**Issue by TeoMonkeyD** [helios-ag/FMElfinderBundle#225]
##### Issue Type:

Please pick one and delete the rest:
- Bug Report
##### Bundle Version:

Master 
##### Summary:

In composer.json you have: **"helios-ag/fm-elfinder-php-connector": "~2.0"**
and it is old for symfony2.8
##### Steps To Reproduce:

I tried to upload an image but ElFinder responded with: **Unable to connect to the backend**.
For correct this error I downloaded last version of Elfinder from this fork https://github.com/helios-ag/ElFinderPHP.

Can you fix this composer.json bug?

**Comment by helios-ag** [comment]
Also note that option "platform" under config node in composer.json make impact on packages versions that composer choose to install. i.e. platform: php: 5.3.9 will constraint elfinder-connector to ~2.4

**Comment by TeoMonkeyD** [comment]
In composer.json I set "php": "5.4" and I changed the require in:

> "helios-ag/fm-elfinder-php-connector": ">=2.5",
> "components/elfinder": ">=2.0"
