### ISSUE TITLE
How to reset the field

### ISSUE THREAD

**Issue by xorgxx** [helios-ag/FMElfinderBundle#227]
Hi
on my form edit : i try to reset the field how is connect to ElFinder, but eatch time i clic on the image field it go strait to ElFinder and i cannot reset to null value the field.

thank

**Comment by helios-ag** [comment]
hi @xorgxx 
You need to override elfinder form type and add for example button that will clear input field.
Or just add button/link on the form that will clear elfinder form(without overriding).
