### ISSUE TITLE
Dynamic path doesn't work after upgrading from 5 to 6

### ISSUE THREAD

**Issue by dipens** [helios-ag/FMElfinderBundle#228]
Bug Report

##### Bundle Version:

Upgrading from `"helios-ag/fm-elfinder-bundle": "~5"`, to `"helios-ag/fm-elfinder-bundle": "~6"`,

##### Summary:

I have a dynamic path setting taking a hint from [this](https://github.com/helios-ag/FMElfinderBundle/issues/91) but after upgrading the file does not seems to upload.

##### Steps To Reproduce:

In the file FM\ElfinderBundle\Configuration\ElFinderConfigurationReader I added this part of code after the `$driverOptions` array definition:

```
$dir="";
parse_str(parse_url($this->requestStack->getCurrentRequest()->server->all()["HTTP_REFERER"])["query"]);
$driverOptions["path"] .= $dir;
if (!is_dir($driverOptions["path"])) {
    if (!mkdir($driverOptions["path"], 0777, true))
    {
        var_dump(error_get_last());
    }
}
$driverOptions["URL"] =  str_replace("/var/www/html/projectName/web/", "", substr($driverOptions["URL"],0,-1).$dir."//");

```
I am using it every where so I need the directory to be dynamic. So I pass the directory to use in the url itself. 
##### Expected Results:

As of 5.0 this was working fine and the files were uploading properly.

##### Actual Results:

After upgrading to 6.0, when I try to upload new files through the bundle, it gives me this error message 

> Upload error.
> No files found for upload.

I am not sure if a better solution is possible or not, but this solution was working properly so far. After the update, this seems to be broken. Could it be done in a better way? If not how can I solve this problem?

Thanks in advance.

**Comment by helios-ag** [comment]
Hi @dipens ,
I tried to reproduce this behaviour, but it works fine, i just placed your code under this line https://github.com/helios-ag/FMElfinderBundle/blob/master/Configuration/ElFinderConfigurationReader.php#L130
preliminarily removed http_referer line

and accessed elfinder via http://local.dev/app_dev.php/elfinder/[instance]/[dynamic_folder]

**Comment by dipens** [comment]
Hello @helios-ag  thanks for getting back at me. I am going to delete and redo the project and see if the issue still persists. I will get back to you.

**Comment by helios-ag** [comment]
@dipens how its going?

**Comment by dipens** [comment]
I recreated the whole project and tried to work with the version 6 multiple times but I still cannot trace the problem down. For now I have downgraded to version 5. I am really not sure what the problem is right now.

**Comment by helios-ag** [comment]
Hi @dipens !
Can you share your composer.json?
Or can you explicitly require helios-ag/fm-elfinder-php-connector: dev-master in composer.json and post your results.

**Comment by dipens** [comment]
This is my composer.json

```json
{
    "name": "root/tsoftdemo",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "require": {
      "php": ">=5.3.9",
      "symfony/symfony": "2.8.*",
      "doctrine/orm": "^2.4.8",
      "doctrine/doctrine-bundle": "~1.4",
      "symfony/swiftmailer-bundle": "~2.3",
      "symfony/monolog-bundle": "~2.4",
      "sensio/distribution-bundle": "~5.0",
      "sensio/framework-extra-bundle": "^3.0.2",
      "incenteev/composer-parameter-handler": "~2.0",
      "thrace/datagrid-bundle":"dev-master",
      "friendsofsymfony/user-bundle": "~2.0@dev",
      "helios-ag/fm-elfinder-bundle": "~6",
      "realestateconz/mssql-bundle": "master-dev",
      "friendsofsymfony/jsrouting-bundle": "dev-master",
      "egeloen/ckeditor-bundle": "dev-master"
    },
    "require-dev": {
        "sensio/generator-bundle": "~3.0",
        "symfony/phpunit-bridge": "~2.7"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin",
        "platform": {
            "php": "5.3.9"
        },
        "component-dir": "web/assets"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}
```


If I run  composer require helios-ag/fm-elfinder-php-connector: dev-master it gives me this error

> [InvalidArgumentException]
>   Could not find package dev-master at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
>

**Comment by helios-ag** [comment]
"platform": {
            "php": "5.3.9"
        },
If you leverage platform version at least to 5.4, it should fetch right connectors version (2.1.5)

**Comment by dipens** [comment]
Hello @helios-ag thank you this was the issue. I upgraded to PHP version 7.0 and it works great.

Thank you for all the help.

**Comment by helios-ag** [comment]
Good to hear that!
