### ISSUE TITLE
Use original library studio-42/elfinder

### ISSUE THREAD

**Issue by hason** [helios-ag/FMElfinderBundle#247]
The fork `helios-ag/fm-elfinder-php-connector` is out of date. Please use original library `studio-42/elfinder` that is more widely used.

**Comment by helios-ag** [comment]
@hason we can't do that, bundle already rely on some features that implemented on this separate library, also elfinder itself is written for old php 5.2 (no namespaces, etc). Only way to be on cuttng edge with elfinder original repo, is to port features from it to connector library (actually it's not hard, mostly copy/paste procedure, but require some attention to details).

**Comment by hason** [comment]
Twig is written for PHP 5.2 without namespaces, also. Original library is using the `elFinder` prefix for all classes.

**Comment by helios-ag** [comment]
In the end i have followed your advice :) Cheers
