### ISSUE TITLE
multiple file select

### ISSUE THREAD

**Issue by ab2llah** [helios-ag/FMElfinderBundle#254]
##### Issue Type:
- Bug Report

Master or exact version, i.e. 6.0.1

hi.i searched every where for this feature and i couldn't find the right config to do this.
when i select one file the select icon is enabled but when i select more, it becomes disabled.
##### Expected Results:

i expected the elfinder to let me select more than one file and return an array of selected files.

but it always gives me one file.

**Comment by ab2llah** [comment]
i already tried changing the commandsOptions multiple to true,but when i do that the select option only becomes enabled and does nothing.not even when i select only 1 file.i mean that it becomes disabled and does nothing but it's not disabled as an html element!

**Comment by helios-ag** [comment]
It's intended behavior, as it used with wysiwyg editors that require single file to return.
Btw you need to override templates, check for example https://github.com/Studio-42/elFinder/issues/1261

**Comment by ahmed-bhs** [comment]
Guys did you find a solution ?
