### ISSUE TITLE
unable to upload image

### ISSUE THREAD

**Issue by simofes** [helios-ag/FMElfinderBundle#255]
- Bug Report

Version, ~ 6.0

When i upload an image it show an error about size like:

Erreur
Erreur lors de l'envoi du fichier.
Les données dépassent la taille maximale allouée.

I have already configured upload max config but the prob persist

Please sir help me
 i like very much your bundle

**Comment by ab2llah** [comment]
did you check your php.ini file?
if you didn't , update these : 
`memory_limit = 32M
upload_max_filesize = 24M
post_max_size = 32M`

**Comment by simofes** [comment]
Thank you for quick response
I alredy have the some parameters ....the error persist

**Comment by simofes** [comment]
i still have the same error !!!!!

**Comment by helios-ag** [comment]
I think issue isn't actual now?
