### ISSUE TITLE
How to preview image and show image thumb?

### ISSUE THREAD

**Issue by winds1983** [helios-ag/FMElfinderBundle#258]
##### Bundle Version:

6.0.1
##### Summary:

Current we use Amazone S3 to manage files, How to preview image and show image thumb when elfinder is loading? current we just show image as a icon with image name.

**Comment by helios-ag** [comment]
Hi @winds1983 this feature is unsupported at this moment.

**Comment by winds1983** [comment]
@helios-ag Could you add it in the future?

**Comment by helios-ag** [comment]
@winds1983 yep, but i will appreciate PR too

**Comment by winds1983** [comment]
@helios-ag ok

**Comment by xorgxx** [comment]
i m using Dev-master, and Sf 3.3.10 and i have the probleme to preview images. is this normal ? all the reste work well. even is create .tmb and .quarantine with all images but different name l1_cGF0dGVyblxwYXR0ZXJuLTEucG5n1508493794.png

**Comment by xorgxx** [comment]
i think i have path probleme

**Comment by xorgxx** [comment]
ok sorry i find the problem. it was dev-master version so i install 6.21
