### ISSUE TITLE
Cant Connect to Backend

### ISSUE THREAD

**Issue by benblub** [helios-ag/FMElfinderBundle#261]
##### Issue Type:

 - Bug Report

##### Bundle Version:

"helios-ag/fm-elfinder-bundle": "^6.2",
Symfony 2.8.9

##### Summary:

Cant connect to Backend @ http://localhost:8000/elfinder?id=form_elfinder
Localhost / win

Exception
Notice: Undefined index: archivers
500 Internal Server Error - ContextErrorException

Stack
in vendor\helios-ag\fm-elfinder-bundle\Configuration\ElFinderConfigurationReader.php at line 132

##### Steps To Reproduce:

Config
http://pastebin.com/qCaPZuk7

Composer Json
http://pastebin.com/UPgpvhJH

**Comment by samanmohamadi** [comment]
I have same problem.

**Comment by benblub** [comment]
Error solved with downgrade FMElfinderBundle to 5.3 but find its a bad solution.

**Comment by helios-ag** [comment]
Investigated, thank you for report, should be fixed by #263, tagged bundle as 6.2.1, upgrade and report back if you have issues too.

**Comment by benblub** [comment]
It works! Thanks
