### ISSUE TITLE
Option buttons issue in modal 

### ISSUE THREAD

**Issue by VictorAtPL** [helios-ag/FMElfinderBundle#266]
##### Issue Type:
- Bug Report
##### Bundle Version:

6.2.1
##### Summary:

When I open elfinder directly via route added to symfony the layout is ok, but when i open modal and inject elfinder to div - the buttons in search panel breaks.
##### Steps To Reproduce:

Initialize elfinder on div.

`{% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <script>
            var opt = {
                url: '{{path('ef_connect')}}/default/{{ app.security.getToken().getUser().getToken() }}',
                lang: 'en'
            };
        </script>
        {% endif %}`

`$(".mediaOpener").click(function () {
            $('#mediaManager').modal("show");
            $('#mediaManager .media-manager').elfinder(opt);
        });`
##### Expected Results:

The search ui shoud look like in direct link to elfinder.
![image](https://cloud.githubusercontent.com/assets/1886347/18345619/8be51e24-75bc-11e6-8849-9ac603c05a70.png)
##### Actual Results:

![image](https://cloud.githubusercontent.com/assets/1886347/18345632/99c95438-75bc-11e6-9006-39eb5fc59769.png)

**Comment by ahmed-bhs** [comment]
@VictorAtPL Any idea how did you integrate elfinder inside a modal. Can you share your code.

**Comment by VictorAtPL** [comment]
@ahmed-bhs I'm sorry, but I did it as a part of commercial project and I don't have access to that code since I finished working at the company which I used to work. I do not remember how I fixed it, too.
