### ISSUE TITLE
Option: URL

### ISSUE THREAD

**Issue by slimiles** [helios-ag/FMElfinderBundle#268]
##### Issue Type:

Please pick one and delete the rest:
 - Documentation Report

##### Bundle Version:

Master

##### Summary:

What kind of file, do I have to put in `url:`?

##### Steps To Reproduce:

I want to initialize the elfinder with Javascript. There is a option called [URL](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#url).

##### Expected Results:

The elfinder is working.

##### Actual Results:

I receive an error: «Unable to connect to backend. Backend not found.»

```
$(document).ready(function() {
    var elf = $('.elfinder').elfinder({
        url : 'php/connector.php',  // connector URL (REQUIRED)
        lang: 'de',             // language (OPTIONAL)
        cssClass: 'explorer',
        height: 450,
        uiOptions: {
            toolbar : [
                // toolbar configuration
                ['mkdir', 'upload'],
                ['search'],
            ]
        },
        contextmenu : {
            files  : [
                'getfile', '|','open', '|', 'copy', 'cut', 'paste', 'duplicate', '|',
                'rm', '|', 'edit', 'rename', '|', 'archive', 'extract', '|', 'info'
            ]
        }
    }).elfinder("instance");
});
```

**Comment by helios-ag** [comment]
Hi @slimiles, the code you provided in your report, is used with standalone elfinder, this bundle utilize twig templates that preconfigured for symfony2/3 usage, for example see https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/views/Elfinder/simple.html.twig#L15

**Comment by slimiles** [comment]
Thanks, I'll check it out! :)
