### ISSUE TITLE
Error on upload : Unknow command

### ISSUE THREAD

**Issue by bartolije** [helios-ag/FMElfinderBundle#271]
##### Issue Type:

Please pick one and delete the rest:
 - Bug Report

##### Bundle Version:
Master

##### Summary:
I setup everything, and I can manage file.
When I try to upload something, I got the error "Unknow command"

Web console give me these errors.

Failed to load resource: the server responded with a status of 404 (Not Found) [...]/web/assets/elfinder/dist/js/i18n/elfinder.en.j
and
elfinder.min.js:10 elfinder debug: [error] [] Unknown command.

**Comment by helios-ag** [comment]
Hi @bartolije, have you added this part to composer.json?
```
{
    "config": {
        "component-dir": "web/assets"
    }
} 
```

**Comment by bartolije** [comment]
Yeah.
I can add image that already are in the folder, but can't upload them without the error

**Comment by helios-ag** [comment]
@bartolije can you post your elfinder configuration (config.yml)?

**Comment by bartolije** [comment]
Hello,

Sure, here it is.

`fm_elfinder:
    instances:
        default:
            locale:           "%locale%"
            editor:           ckeditor
            fullscreen:       false
            include_assets:   true
            connector:
                debug:        false
                roots:
                    uploads:
                        driver:           LocalFileSystem
                        path:             assets/uploads
                        upload_allow:     ['image/png', 'image/jpg', 'image/jpeg' 'application/zip', 'application/pdf']
                        upload_deny:      ['all']
                        upload_max_size:  16M

ivory_ck_editor:
    default_config:    base_config
    configs:
        base_config:
            toolbar:                    full
            filebrowserBrowseRoute:     elfinder
            filebrowserBrowseRouteParameters:
                instance: default`

**Comment by bartolije** [comment]
`sdf`
