### ISSUE TITLE
Upload failure on symfony 2.7.*

### ISSUE THREAD

**Issue by alencarcabral** [helios-ag/FMElfinderBundle#272]
##### Issue Type:

Please pick one and delete the rest:

 - Bug Report

##### Bundle Version:

Master 

##### Summary:

Upload´s failare using fm-elfinder-bundle in the symfony 2.7.* 

On symfony 2.8.* it´s ok.

To solve the problem, just copied the folder's vendor/helios-ag and web/assets/elfinder, from folder on symfony version 2.8.*  to the folder on symfony version 2.7.

after copy,  fm-elfinder-bundle on the symfony 2.7.*, works fine and i can do uploads.

##### Steps To Reproduce:

install bundle, default configuration.
composer command used "composer update helios-ag/fm-elfinder-bundle"
the same steps used in both version of symfony

after install try to upolad file,
on symfony 2.7.* uploa´s failure.

##### Expected Results:

upload´s  sucess on symfony 2.7.*

##### Actual Results:

upload´s  failure on symfony 2.7.*

** Could be the problem the aviable version of  fm-elfinder-bundle for symfony 2.7?
A worng file for symfony 2.7?

tks

**Comment by helios-ag** [comment]
Thanks for report, i'll check it out
