### ISSUE TITLE
How to assign a home folder to a user?

### ISSUE THREAD

**Issue by xorgxx** [helios-ag/FMElfinderBundle#276]
Hi all is in the title : How to assign a home folder to a user?

thank for any help.

Version: Windons 10 x64, SF3.2, "helios-ag/fm-elfinder-bundle": "^6.1",

**Comment by nicolasmure** [comment]
Hi,

As you [asked earlier](https://github.com/helios-ag/FMElfinderBundle/issues/138#issuecomment-271137499), you can checkout https://github.com/helios-ag/elfinder-userbundle-example .

According to [the doc](https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/doc/ckeditor-integration.md#step-2-configure-ckeditor-setting-via-settingsyml-or-through-form-builder), you have to specify the home folder of your user when building the form type.

The workflow could be :
- when a user is created, create a folder for that user (based on the user ID for instance)
- when you're building the form, indicate the homeFolder to use for the currently logged in user (the user ID for instance).

**Comment by xorgxx** [comment]
thank, so this exemple that you give is still valide to do this ?

**Comment by xorgxx** [comment]
and i have one more probleme if i overwrite the elfinder configuration all access will be and i dont want this! i want only the "member" part

**Comment by xorgxx** [comment]
i find this how is not bad to, and more easy ? 
    ```
<script>$(document).on("click", "[data-type='elfinder-input-field'][id='profilebundle_profile_img']", function() { var childWin = window.open("{{path('elfinder', {'instance': "btnfile", 'homeFolder': "orders" })}}", "popupWindow", "height=450, width=900"); });</script>
```

**Comment by nicolasmure** [comment]
Yes I think it would do the trick.
You should also override the `elfinder` route to assert that the logged in user is allowed to access to the specified home folder : 
```php
/**
 * @Route("/elfinder/{instance}/{homeFolder}")
 */
public function showAction(Request $request, $instance, $homeFolder)
{
    // get the $user
    // if (!$user is allowed to access $homeFolder) {
    //     throw $this->createAccessDeniedException();
    // }

    return $this->forward('FMElfinderBundle:ElFinder:show', array(
        'instance' => $instance,
        'homeFolder' => $homeFolder,
    ));
}
```
