### ISSUE TITLE
Is is possible to create unique filenames?

### ISSUE THREAD

**Issue by jakobeissler** [helios-ag/FMElfinderBundle#279]
##### Issue Type:

 - Documentation Report

##### Bundle Version:

Master 

##### Summary:

Is it possible to create unique filenames on upload so i don't get duplicates and editor don't ask me to overwrite? Should work with option "uploadOverwrite" but couldn't make it work.

**Comment by jakobeissler** [comment]
I'm closing this one, i missed that option in the docs

**Comment by helios-ag** [comment]
@jakobeissler hi, yes there is no existing plugin for elfinder that can help you with your problem, but if you look under [Sanitizer](https://github.com/helios-ag/ElFinderPHP/blob/master/src/Plugins/Sanitizer/plugin.php) plugin, this can lead you to a possible solution with creating own plugin.

**Comment by jakobeissler** [comment]
I got this working with the upload_overwrite option in config.yml.
