### ISSUE TITLE
is there any way to disable/enable commands using config.yml

### ISSUE THREAD

**Issue by amehta1605** [helios-ag/FMElfinderBundle#281]
##### Issue Type:

 - Feature Idea

##### Bundle Version:

Master

##### Summary:

As I configured FMElfinderBundle, I didn't find any way to enable/disable commands from config file, I did it by extending view and add directly to javascript configution of elfinder. 
 
##### Expected:

As core Elfinder provide functionality to enable/disable command, we can also provide option for it in config like we have option for url and onlyMime.

**Comment by helios-ag** [comment]
@amehta1605 
You can use `disabled_commands` key under one of your roots
https://github.com/helios-ag/FMElfinderBundle/blob/master/DependencyInjection/Configuration.php#L148

**Comment by amehta1605** [comment]
@helios-ag 

got it..Thankyou so much!  please add it somewhere in documentation.. it will be very help-full..

**Comment by helios-ag** [comment]
@amehta1605 feel free to contribute :)
