### ISSUE TITLE
Notice: Undefined index: instance_name stfalcon_tinymce

### ISSUE THREAD

**Issue by lykich99** [helios-ag/FMElfinderBundle#285]
##### Issue Type:
     - Bug Report

##### Bundle Version:

Master or exact version, i.e. 6.0.1

##### Summary:
I use tinymce4, when I click to button in open widows I see next error.
<pre>
Notice: Undefined index: instance_name
500 Internal Server Error - ContextErrorException
</pre>
Log
<pre>
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined index: instance_name" at /../../../../www/vendor/helios-ag/fm-elfinder-bundle/Controller/ElFinderController.php line 36
</pre>
##### Steps To Reproduce:

config.yml
<pre>
fm_elfinder:
    instances:
        default:
            locale: %locale%
            editor: tinymce4 
            fullscreen: true 
            include_assets: true 
            connector:
                debug: true          
                roots:  
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M 
                      

stfalcon_tinymce:    
      tinymce_jquery: false    
      selector: ".tinymce"     
      language: %locale%
      theme:         
        simple:             
          theme: "advanced" 
          file_browser_callback : elFinderBrowser
          relative_urls: false        
          plugins: "advlist autolink link image lists charmap preview hr anchor pagebreak searchreplace wordcount visualblocks visualchars code insertdatetime media nonbreaking table contextmenu directionality emoticons paste textcolor "                
          toolbar: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect forecolor backcolor | link unlink anchor | image media | preview code "

</pre>

twig
<pre>

  {{ elfinder_tinymce_init4('instance_name',{'width':'900', 'height': '850', 'title':'ElFinder 2.0'} ) }}
   {{ tinymce_init({ theme: {'simple':{'language': app.request.locale, 'height': 400 }} }) }}

</pre>

**Comment by helios-ag** [comment]
I think it's not a bug, because your

{{ elfinder_tinymce_init4('**instance_name**',{'width':'900', 'height': '850', 'title':'ElFinder 2.0'} ) }}

should be **default**, i.e. its a key under **instances** node in configuration

**Comment by lykich99** [comment]
Thanks.
I changed values for deafult and now have next situation in the open window loaded iframe on route http://site.com/elfinder and have error No route found.
I made dir /upload/bob and see editor on the next url http://site.com/elfinder/default/bob#elf_l1_Lw.
What values I have  to configured?

**Comment by helios-ag** [comment]
@lykich99, have you registered elfinder routing file?

**Comment by helios-ag** [comment]
I forked [symfony-standard](https://github.com/helios-ag/symfony-standard/tree/elfinder), check out `elfinder` branch and install deps via composer. 
Tinymce example placed under url 'http://127.0.0.1:8000/tinymce',
I have used this [TinymceBundle](https://github.com/stfalcon/TinymceBundle)

**Comment by lykich99** [comment]
Thanks.
I used TinymceBundle,Symfony 2.8. After testing I will reply this.

**Comment by helios-ag** [comment]
Closed to inactivity.
