### ISSUE TITLE
El finder showing folder not found. 

### ISSUE THREAD

**Issue by morwalz** [helios-ag/FMElfinderBundle#286]
Hi, I am working with module with Symphony CMF. I am getting folder not found in windows. Though same code work fine in Mac. 
![image](https://cloud.githubusercontent.com/assets/3679081/26322193/76c1df00-3f47-11e7-8ffb-da479b1a35c4.png)
Any fix ?
Update : I tried on mac. Same setting works. Any one here to help ?

**Comment by helios-ag** [comment]
@morwalz thanks for report, but can you open chrome/firefox console and check what error you have in response?

**Comment by morwalz** [comment]
there is no error in the console. I tried it  on mac it works fine, Now i installed on vagrant ubuntu machine. again work very well. But still there is no solution for windows. Please help

**Comment by manu-sparheld** [comment]
solution is you don't have that directory created in your project.
