### ISSUE TITLE
Is there any way to disabled/remove some actions based on the user role

### ISSUE THREAD

**Issue by dipens** [helios-ag/FMElfinderBundle#289]
##### Issue Type:
 - Feature Idea

##### Bundle Version:
6

##### Summary:
I am using your bundle and it works great. One feature that I would like to have is that, depending on the user role, I should be able to disable/remove some actions. For example only an admin can delete files/folder

##### Steps To Reproduce:
1.  Try to delete a file as an admin
2.  Try to delete a file as a regular user

##### Expected Results:
1.  File deleted
2.  File not deleted/not able to delete/delete button disabled

**Comment by Mysh3ll** [comment]
Hi, I'm interested too for this feature.
