### ISSUE TITLE
Symfony 4 compatibility

### ISSUE THREAD

**Issue by RubixR4** [helios-ag/FMElfinderBundle#299]
##### Issue Type:

 - Compatibility issue

##### Bundle Version:

Master

##### Summary:

Hi, thank you for your bundle that I used with TinyMCE and Symfony 3. It works great but I tried to use it with Symfony 4 and I have some errors. I saw that the master branch was not prepared for Symfony 4 yet... :'( Do you know when you will update the bundle ?

Thank you again for your work.

**Comment by helios-ag** [comment]
Hi @RubixR4 
have you tried version 7.0? (master branch is currently used for sf3, i have separate branch for symfony 4 named sf4)
also it have recipe https://github.com/symfony/recipes-contrib/tree/master/helios-ag/fm-elfinder-bundle/7.0

**Comment by RubixR4** [comment]
Hi @helios-ag,

I tried version 7.0 but I have an error. It looks like file "vendor/helios-ag/fm-elfinder-bundle/Twig/Extension/FMElfinderExtension.php" tries to render the template with the 'old' syntax. Is it still possible to use it now that Symfony 4 use dedicated "templates" folder ?

Thanks

![elfinder](https://user-images.githubusercontent.com/845236/35017564-aa6577f8-fb1d-11e7-88f2-af337f6da3b5.jpg)

**Comment by Sentence** [comment]
Same issue with Symfony 3.4 (uses the new structures, like 4) with CKEditor (IvoryCKEditorBundle) like @RubixR4.

`Unable to find template "FMElfinderBundle:Form:elfinder_widget.html.twig"`

**Comment by RubixR4** [comment]
Proposed a patch for SF4.
