### ISSUE TITLE
Update to latest version of elFinder

### ISSUE THREAD

**Issue by mrmadhav** [helios-ag/FMElfinderBundle#301]
##### Issue Type:

 - Bug Report

##### Bundle Version:

Master

##### Summary:

Currently the version of this module uses version 2.1 of elFinder. However as it can be seen on elFinder's github page (here: https://github.com/Studio-42/elFinder), the version 2.1 is not recommended as it may cause serious damage to our servers. 

I have personally experienced this firsthand with one of my clients where renaming a file would crash elFinder or moving files would overwrite whole directories.

Can you please update the module to support the latest version of elFinder ?

**Comment by helios-ag** [comment]
I agreed that we need to update, but it also require to backport some features that was introduced to library to work with bundle

**Comment by mrmadhav** [comment]
Hi @helios-ag 

Thanks for the reply. Do you currently have a timeline for this or have you planned when you are expecting it to happen ?

If you already know what needs to be modified etc, maybe I can help doing the code migration ?

Best Regards,
Madhav

**Comment by helios-ag** [comment]
Hi @mrmadhav 
Unfortunately there is no timeline for this, as i dont have much free time to do so.
If you want to help, take latest elfinder and by comparing with current revision of ElFinder lib, 
add namespaces and backport some methods that was added to ElFinder.php class (i.e. https://github.com/helios-ag/ElFinderPHP/commit/23446f17dcb72360305eaef8cfe1fd9bfdab966f)

**Comment by helios-ag** [comment]
Updated in `dev` branch, need to resolve some issues with unit tests and didn't check with flysystem driver yet, but local and mysql works fine.

**Comment by pribeirojtm** [comment]
Hello. It is not yet possible to use this bundle with the lastest version of studio-42/elfinder ?
Thanks

**Comment by helios-ag** [comment]
@pribeirojtm you can send PR against https://github.com/helios-ag/elfinder-component to update elfinder assets
