### ISSUE TITLE
Max upload size

### ISSUE THREAD

**Issue by olivier1208** [helios-ag/FMElfinderBundle#311]
##### Issue Type:

Please pick one and delete the rest:
 - Bug Report

##### Bundle Version:

Master

##### Summary:

Please explain the problem briefly.

##### Steps To Reproduce:

Only on shared hosting
No troubles in local or in our staging server
Uploading a file or deleting a file

##### Expected Results:

No error messages

##### Actual Results:

When uploading a file i get

{error: ["errUpload", "errUploadTotalSize"]}
error
:
["errUpload", "errUploadTotalSize"]
0
:
"errUpload"
1
:
"errUploadTotalSize"

I've check the php.ini, checked all the values, but nothing helps.

When deleting a file this error is thrown
warning
:
["errRm", "user_1/", "errFileNotFound"]
0
:
"errRm"
1
:
"user_1/"
2
:
"errFileNotFound"

Indeed when refreshing the page the file is well download / or deleted.

Where it may come from ??

Thanks

**Comment by helios-ag** [comment]
Hi @olivier1208 
Only one thing i could suspect is "post_max_size" in php.ini settings.

**Comment by olivier1208** [comment]
Hi
@helios-ag 
Thanks for your reply

Here's my php.ini values

**Comment by helios-ag** [comment]
Can you post `fm_elfinder` config? (from config.yml)

**Comment by olivier1208** [comment]
`fm_elfinder:
    assets_path: '../web/assets' # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            locale: "%locale%" # defaults to current request locale
            cors_support: true # allows cross domain responses handling (default false)
            editor: form # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
#            path_prefix: /jf_admin # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            fullscreen: true # default is true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to manage loading of javascript and css assets manually
            visible_mime_types: ['image', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'] # only show these mime types, defaults to show all
            connector:
                binds:
                    upload.presave:
                        - Plugin.Sanitizer.onUpLoadPreSave
                debug: true # defaults to false
                plugins:
                    Sanitizer:
                        enable: true
                        targets: ['(',' ',')','[',']','{','}','\','/',':','*','?','"','<','>','|',' ','''','à','á','â','ã','ä','ç','è','é','ê','ë','ì','í','î','ï','ñ','ò','ó','ô','õ','ö','ù','ú','û','ü','ý','ÿ','À','Á','Â','Ã','Ä','Ç','È','É','Ê','Ë','Ì','Í','Î','Ï','Ñ','Ò','Ó','Ô','Õ','Ö','Ù','Ú','Û','Ü','Ý']
                        replace: '_'
                    AutoResize: # global resize options, applies to root which don't have his own resize configuraion
                        enable: false
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/user_files
                        plugins:
                            Sanitizer:
                                enable: true
                                targets: [' ','(',' ',')','[',']','{','}','\','/',':','*','?','"','<','>','|',' ','''','à','á','â','ã','ä','ç','è','é','ê','ë','ì','í','î','ï','ñ','ò','ó','ô','õ','ö','ù','ú','û','ü','ý','ÿ','À','Á','Â','Ã','Ä','Ç','È','É','Ê','Ë','Ì','Í','Î','Ï','Ñ','Ò','Ó','Ô','Õ','Ö','Ù','Ú','Û','Ü','Ý']
                                replace: '_'
                        upload_allow: ['image', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'] #['image/png', 'image/jpg', 'image/jpeg']
                        # upload_deny: ['all']
                        upload_max_size: 10M # also file upload sizes restricted in php.ini
                        attributes: #example of setting attributes permission
                            - { pattern: '/(.*?)/', read: true, write: true, locked: false}

`

**Comment by olivier1208** [comment]
Got it ?

**Comment by olivier1208** [comment]
Argh my bad !
