### ISSUE TITLE
version 8 doesn't work with symfony-cmf/media-bundle

### ISSUE THREAD

**Issue by wuestkamp** [helios-ag/FMElfinderBundle#313]
##### Issue Type:
 - Bug Report

##### Bundle Version:
Master

##### Summary:
Adapter from symfony-cmf/media-bundle not working

##### Steps To Reproduce:
In your composer.json use:

```
"helios-ag/fm-elfinder-bundle": "8.x",
"symfony-cmf/media-bundle": "1.3.*"
```
Then run "composer install --no-dev"

##### Expected Results:

No error.

##### Actual Results:

This error occurs:

```

ClassNotFoundException in PhpcrDriver.php line 35:
Attempted to load class "ElFinderVolumeDriver" from namespace "FM\ElFinderPHP\Driver".
Did you forget a "use" statement for another namespace?
```

So the symfony-cmf/media-bundle uses the ElFinderVolumeDriver from helios-ag/fm-elfinder-php-connector. As this is deprecated how should this work?

Thanks!
Kim

**Comment by helios-ag** [comment]
@wuestkamp i think we can close this issue, according to this https://github.com/symfony-cmf/media-bundle/pull/179 ?
