### ISSUE TITLE
JqueryUi name mismatch

### ISSUE THREAD

**Issue by verschoof** [helios-ag/FMElfinderBundle#314]
##### Issue Type:

Please pick one and delete the rest:
 - Bug Report

##### Bundle Version:

composer.lock
```
"name": "components/elfinder",
"version": "2.2"
...
"name": "components/jquery",
"version": "3.3.1",
...
"name": "components/jqueryui",
"version": "1.12.1",
...
```

##### Steps To Reproduce:

I use Grunt to setup the assets, that means, I copy `vendor/components` to `web/assets`.

```
elfinder: {
    src: '**',
    cwd: 'vendor/components',
    dest: 'web/assets/',
    expand: true,
    flatten: false
}
```

```
$ ls -la vendor/components/
elfinder
jquery
jqueryui
```

##### Expected Results:

I expect the requested file should be on `assets/jqueryui/jquery-ui.min.js`

##### Actual Results:

Elfinder request routes: `assets/jquery-ui/jquery-ui.min.js` 

https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/views/Elfinder/helper/assets_js.html.twig#L2

**Comment by helios-ag** [comment]
It's not a bug, we rely on components installer, which moves jqueryui to jquery-ui directory. You can try override twig template with your own paths if you wish.
