### ISSUE TITLE
Migrate to FOSCKEditorBundle

### ISSUE THREAD

**Issue by bobvandevijver** [helios-ag/FMElfinderBundle#316]
##### Issue Type:

 - Feature Idea

##### Bundle Version:

Master

##### Summary:

According to the [Symfony docs](https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html), the Ivory bundle has been abandoned (As IvoryCKEditorBundle was abandoned, FriendsOfSymfony took this bundle over, to help you easily migrate just [follow our guide.](https://symfony.com/doc/current/bundles/FOSCKEditorBundle/migration.html)).  

This bundle should probably also migrate to the new CKEditorBundle. I'm currently using the new FOS bundle together with this bundle, without any problems.

**Comment by helios-ag** [comment]
Thanks for pointing that, definetely worth to mention in docs this :+1:

**Comment by helios-ag** [comment]
Resolved, tagged as 8.0.2
