### ISSUE TITLE
Twig error after updating

### ISSUE THREAD

**Issue by grimmlink** [helios-ag/FMElfinderBundle#330]
##### Issue Type:

 - Bug Report

##### Bundle Version:

 - 8.0.3

##### Summary:

After updating the bundle i get this error:

> Type error: Argument 1 passed to Twig_Environment::addExtension() must implement interface Twig_ExtensionInterface, boolean given, called in /data/www/dev/odt/marketplace/var/cache/dev/ContainerEitix01/appDevDebugProjectContainer.php on line 1795

The line in question:

`$instance->addExtension(${($_ = isset($this->services['twig.extension.fm_elfinder_init']) ? $this->services['twig.extension.fm_elfinder_init'] : $this->getTwig_Extension_FmElfinderInitService()) && false ?: '_'});`

##### Steps To Reproduce:

Updated from version 6 to version 8.
I'm using sf3.4

##### Composer.json

```json
        "php": ">=5.5.9",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "incenteev/composer-parameter-handler": "^2.0",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^5.0.0",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/symfony": "3.4.*",
        "twig/twig": "^1.0||^2.0",

        "twig/extensions": "^1.5",
        "stof/doctrine-extensions-bundle": "~1.2",
        "friendsofsymfony/user-bundle": "~2.0",
        "geoip2/geoip2": "~2.0",
        "liip/imagine-bundle": "^1.9",
        "nelmio/cors-bundle": "^1.5",
        "grimmlink/mangopay-bundle": "dev-master",
        "vich/uploader-bundle": "^1.6",
        "willdurand/js-translation-bundle": "^2.6",
        "friendsofsymfony/ckeditor-bundle": "^1.1",
        "friendsofsymfony/jsrouting-bundle": "^2.2",
        "mangopay/php-sdk-v2": "^2.7",
        "algolia/search-bundle": "^3.1",
        "anthonymartin/geo-location": "^1.0",
        "presta/image-bundle": "^1.8",
        "helios-ag/fm-elfinder-bundle": "~8"
```

**Comment by tifabien** [comment]
Seems the error is not coming from your bundle upgrade 6->8 but seems related to the latest Symfony 3.4.16 version. I didn't have the error when running Symfony 3.4.15

**Comment by tifabien** [comment]
Confirmed. 
It's a Symfony issue and tracked here : https://github.com/symfony/symfony/issues/28658

**Comment by helios-ag** [comment]
Thanks for reporting guys, looks like we need to wait hotfix in symfony repo.

**Comment by grimmlink** [comment]
Aaah the issue wasn't declared when I searched for it.
Thanks for your time !
