### ISSUE TITLE
chunk upload feature

### ISSUE THREAD

**Issue by l396635210** [helios-ag/FMElfinderBundle#358]
##### Issue Type:
 - Feature Idea
hi! elfinder has suported chunk upload .[uploadmaxconn](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadmaxconn-elfinder--2112)

##### Summary:

Please update the Feature， Please .QQQ!

**Comment by helios-ag** [comment]
Added in 10.0.3 (#392 )
