### ISSUE TITLE
upload error in phone browser but works fine in the computer

### ISSUE THREAD

**Issue by Azraelir** [helios-ag/FMElfinderBundle#364]
##### Issue Type:

Please pick one and delete the rest:
 - Bug Report

##### Bundle Version:

"helios-ag/fm-elfinder-bundle": "^8.0",

##### Summary:

I have these config:

`sectionava:`
`            relative_path: true`
`            editor: form # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom`
`            include_assets: true # disable if you want to manage loading of javascript and css assets manually`
`            visible_mime_types: ['video/mp4' , 'video/mpeg', 'video/x-mpeg', 'video/mpeg', 'video/quicktime' , 'audio/mpeg', 'audio/mp3', 'audio/mpeg3', 'audio/x-mpeg-3', 'audio/wav', 'audio/x-wav'] # only show these mime types, defaults to show all`
`            connector:`
`                roots:       # at least one root must be defined, defines root filemanager directories`
`                    uploads:`
`                        accepted_name: '/^[^\.].*/'   #<<< this is default`
`                        driver: LocalFileSystem`
`                        path: uploads/section/videos`
`                        upload_allow: ['video/mp4' , 'video/mpeg', 'video/x-mpeg', 'video/mpeg', 'video/quicktime' , 'audio/mpeg', 'audio/mp3', 'audio/mpeg3', 'audio/x-mpeg-3', 'audio/wav', 'audio/x-wav']`
`                        upload_deny: ['all']`
`                        upload_max_size: 201M # also file upload sizes restricted in php.ini`

I can upload audio file in my computer just file but when I access the elfinder with chrome 75 on my phone, it doesn't allow upload of the same audio file and says the file is not supported.

**Comment by helios-ag** [comment]
Closing as inactive, and version of bundle bumped few times. Feel free to reopen.
