### ISSUE TITLE
PHP 7.2 Function create_function() is deprecated

### ISSUE THREAD

**Issue by abdallahmaali** [helios-ag/FMElfinderBundle#376]
**Hello I'm using this bundle with my Symfony project after I upgrade my server PHP  to PHP 7.2
I get this error, any idea how I can fix it ?**

`Invalid backend response.
Data is not JSON.
<br /> <b>Deprecated</b>: Function create_function() is deprecated in <b>/home/aqar/public_html/daman/vendor/helios-ag/fm-elfinder-php-connector/src/ElFinder.php</b> on line <b>347</b><br /> <br /> <b>Deprecated</b>: Function create_function() is deprecated in <b>/home/aqar/public_html/daman/vendor/helios-ag/fm-elfinder-php-connector/src/ElFinder.php</b> on line <b>347</b><br /> <br /> <b>Deprecated</b>: Function create_function() is deprecated in <b>/home/aqar/public_html/daman/vendor/helios-ag/fm-elfinder-php-connector/src/ElFinder.php</b> on line <b>347</b><br /> <br /> <b>Warning</b>: Cannot modify header information - headers already sent by (output started at /home/aqar/public_html/daman/vendor/helios-ag/fm-elfinder-php-connector/src/ElFinder.php:347) in <b>/home/aqar/public_html/daman/vendor/helios-ag/fm-elfinder-php-connector/src/Connector/ElFinderConnector.php</b> on line <b>142</b><br /> {"cwd":{"isowner":false,"ts":1552730555,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_Lw","name":"land_340","csscls":"elfinder-navbar-root-local","uiCmdMap":[],"disabled":["chmod"],"volumeid":"l1_","locked":1,"dirs":1,"tmbUrl":"http:\/\/aqar.ps\/daman\/web\/uploads\/land_340\/.tmb\/","root":"l1_Lw"},"options":{"path":"land_340","url":"http:\/\/aqar.ps\/daman\/web\/uploads\/land_340\/","tmbUrl":"http:\/\/aqar.ps\/daman\/web\/uploads\/land_340\/.tmb\/","disabled":["chmod"],"separator":"\/","copyOverwrite":1,"uploadOverwrite":1,"uploadMaxSize":15728640,"dispInlineRegex":"^(?:(?:image|text)|application\/x-shockwave-flash$)","jpgQuality":100,"archivers":{"create":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/x-xz","application\/zip"],"extract":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/x-xz","application\/zip"],"createext":{"application\/x-tar":"tar","application\/x-gzip":"tgz","application\/x-bzip2":"tbz","application\/x-xz":"xz","application\/zip":"zip"}},"uiCmdMap":[],"syncChkAsTs":1,"syncMinMs":10000},"files":[{"isowner":false,"ts":1552730555,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_Lw","name":"land_340","csscls":"elfinder-navbar-root-local","uiCmdMap":[],"disabled":["chmod"],"volumeid":"l1_","locked":1,"dirs":1,"tmbUrl":"http:\/\/aqar.ps\/daman\/web\/uploads\/land_340\/.tmb\/"},{"isowner":false,"mime":"directory","ts":1552730533,"read":1,"write":1,"size":0,"hash":"l1_QWVyaWFsX2ltYWdlcw","name":"Aerial_images","phash":"l1_Lw","volumeid":"l1_"},{"isowner":false,"mime":"directory","ts":1543240311,"read":1,"write":1,"size":0,"hash":"l1_U2tldGNo","name":"Sketch","phash":"l1_Lw","volumeid":"l1_"},{"isowner":false,"mime":"directory","ts":1543240311,"read":1,"write":1,"size":0,"hash":"l1_TGVnYWxQYXBlcg","name":"LegalPaper","phash":"l1_Lw","volumeid":"l1_","dirs":1},{"isowner":false,"mime":"directory","ts":1543240311,"read":1,"write":1,"size":0,"hash":"l1_U2l0ZV9tYXA","name":"Site_map","phash":"l1_Lw","volumeid":"l1_"},{"isowner":false,"mime":"application\/pdf","ts":1552730555,"read":1,"write":1,"size":"934578","hash":"l1_MTkxLTIucGRm","name":"191-2.pdf","phash":"l1_Lw"},{"isowner":false,"mime":"directory","ts":1543240311,"read":1,"write":1,"size":0,"hash":"l1_YnVpbGRpbmdz","name":"buildings","phash":"l1_Lw","volumeid":"l1_"},{"isowner":false,"mime":"directory","ts":1543240311,"read":1,"write":1,"size":0,"hash":"l1_U3VydmV5","name":"Survey","phash":"l1_Lw","volumeid":"l1_"},{"isowner":false,"mime":"directory","ts":1552726142,"read":1,"write":1,"size":0,"hash":"l1_UmVhbF9pbWFnZXM","name":"Real_images","phash":"l1_Lw","volumeid":"l1_"}],"api":"2.1","uplMaxSize":"2M","uplMaxFile":"20","netDrivers":[],"debug":{"connector":"php","phpver":"7.2.25","time":0.3307077884674072265625,"memory":"8326Kb \/ 6279Kb \/ -1","upload":"","volumes":[{"id":"l1_","name":"\\driver\\elfindervolumelocalfilesystem","mimeDetect":"finfo","imgLib":"gd"}],"mountErrors":[]}}`

**Comment by helios-ag** [comment]
Hi @abdallahmaali 
Looks like you are using very old bundle version, which rely on elfinder php connector library (which relies on create_function(), and [deprecated](https://www.php.net/manual/en/function.create-function.php) since php 7.2), which isn't maintained anymore. 
I suggest to upgrade bundle.

**Comment by abdallahmaali** [comment]
ok thank you i made an update for the bundle by this following step

1- update the version in composer.json file like this 

`{
    "require": {
        "helios-ag/fm-elfinder-bundle": "~9",
    }
}`


2- update composer by the following command 
`composer update helios-ag/fm-elfinder-bundle
`
I'm not sure if these steps are the correct way to upgrade the bundle?

**Comment by helios-ag** [comment]
Or you can simply `composer require helios-ag/fm-elfinder-bundle ^9`

**Comment by helios-ag** [comment]
And check docs, probably something has changed since.

**Comment by abdallahmaali** [comment]
ok thank you tried to make an update but I get the following error message :



`  Problem 1

    - Conclusion: don't install helios-ag/fm-elfinder-bundle 9.3.2
    - Conclusion: don't install helios-ag/fm-elfinder-bundle 9.3.1
    - Conclusion: don't install helios-ag/fm-elfinder-bundle 9.3
    - Conclusion: don't install helios-ag/fm-elfinder-bundle 9.2.1
    - Conclusion: don't install helios-ag/fm-elfinder-bundle 9.2
    - Conclusion: don't install helios-ag/fm-elfinder-bundle 9.1.1
    - Conclusion: don't install helios-ag/fm-elfinder-bundle 9.1
    - Conclusion: don't install helios-ag/fm-elfinder-bundle 9
    - Conclusion: remove components/elfinder 2.2
    - Installation request for helios-ag/fm-elfinder-bundle ^9 -> satisfiable by helios-ag/fm-elfinder-bundle[9.1, 9.1.1, 9.2, 9.2.1, 9.3, 9.3.1, 9.3.2, 9.0.x-dev, 9].
    - Conclusion: don't install components/elfinder 2.2
    - helios-ag/fm-elfinder-bundle 9.0.x-dev requires components/elfinder ~3 -> satisfiable by components/elfinder[3.0, 3.0-alpha, 3.1, 3.1.1, 3.1.2, 3.1.3].
    - Can only install one of: components/elfinder[3.0, 2.2].
    - Can only install one of: components/elfinder[3.0-alpha, 2.2].
    - Can only install one of: components/elfinder[3.1, 2.2].
    - Can only install one of: components/elfinder[3.1.1, 2.2]. 
    - Can only install one of: components/elfinder[3.1.2, 2.2].
    - Can only install one of: components/elfinder[3.1.3, 2.2].
    - Installation request for components/elfinder (locked at 2.2) -> satisfiable by components/elfinder[2.2].`

any suggestions please and sorry because i think this a composer issues

**Comment by helios-ag** [comment]
Probably you have explicit dep for `components/elfinder` in your composer.json.
Remove it, bundle already have dependency on proper version.
