### ISSUE TITLE
baseUrl configuration

### ISSUE THREAD

**Issue by shundaime** [helios-ag/FMElfinderBundle#397]
Hi, 

We have an issue with your bundle on main.js.twig config 
The baseUrl path stop us to work on local.

Actually the path is **'/bundles/fmelfinder/js'**
And when we change it by '**bundles/fmelfinder/js**' it's working ! 

Would you be so kind to remove the slash in font of bundles ?

Best regards.

**Comment by helios-ag** [comment]
Tagged as 10.0.4, 
PR #394 Should solve your issue
