### ISSUE TITLE
Missing upgrade notes?

### ISSUE THREAD

**Issue by mikemix** [helios-ag/FMElfinderBundle#405]
**Short description of what this feature will allow to do:**
How to update from v9 to v10?

**Example of how to use this feature**
Especially what to do with missing options? `include_assets` is now gone.

**Comment by qdequippe** [comment]
@mikemix did you find how to upgrade? I am also looking for an upgrade note

**Comment by mikemix** [comment]
Nope.

**Comment by MaximeMazet** [comment]
If you and to update to the version 10 you need to replace in your compose.json the version

**Comment by qdequippe** [comment]
@MaximeMazet yes of course :) 
I am working with a deep integration of this bundle into a project and I need to know/check all BC breaks and how to upgrade it

**Comment by helios-ag** [comment]
Well, short changes declared in release notes. For easy comparing changes you can use compare between tags, for example: 
https://github.com/helios-ag/FMElfinderBundle/compare/9.3.2...10.1#diff-ebe00144d6cecb5ca8a2860883e01147f42bbed2b12a3a7f44915908a4829faa
