### ISSUE TITLE
Very slow for large data

### ISSUE THREAD

**Issue by bhaktaraz** [helios-ag/FMElfinderBundle#410]
I've reached almost 4 GB of image upload. Now when I open the folder it is a nightmare. It took 40 sec - 50 sec time to load images. 

**Is there any way to load only few images at a time and load more while scrolling or sth else?**

My server configuration is 2 GB RAM, 1 CPU, 50TB SSD Storage, 2 TB Transfer, and my internet speed is 10 MB/S.

**Comment by MaximeMazet** [comment]
Hi

It's normal 4GB of image is very very large ;)

**Comment by bhaktaraz** [comment]
So, this bundle is not for large data? I've also asked the question above that **Is there any way to load only a few images at a time and load more while scrolling or sth else?** What is your view on it @MaximeMazet

**Comment by MaximeMazet** [comment]
Hello
This bundle is for connect ElFinder to Symfony not for upgrade ElFinder
