### ISSUE TITLE
Unable to run elfinder:install via absolute path

### ISSUE THREAD

**Issue by mboron83** [helios-ag/FMElfinderBundle#431]
**Describtion of the bug**
While running elfinder:install command I'm getting such error:

> In Filesystem.php line 538:
>                                                                                  
>   The origin directory specified "vendor/studio-42/elfinder/css" was not found.  
> 

**Steps to Reproduce**
1) I go to my homepage directory e.g. 
`cd /home/myuser`

2) I'm trying to run elfinder:install command using **absolute path** to my project e.g. 
` /var/www/example.com/bin/console elfinder:install`

I guess the problem is finding proper path to css because when I'm inside root directory of my project everything works fine.
```
cd /var/www/example.com
bin/console elfinder:install
elFinder assets successfully installed
```

**Comment by helios-ag** [comment]
Closing via #418
