### ISSUE TITLE
Deprecation (Since Symfony 5.3) : RegisterListenersPass configuration

### ISSUE THREAD

**Issue by amalricBzh** [helios-ag/FMElfinderBundle#456]
**Describe the bug**
Using FMElfinderBundle (v10.1), Symfony (5.3.7) throw a deprecation warning :

`Since symfony/event-dispatcher 5.3: Configuring "Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass" is deprecated.`

**To Reproduce**
Use FMElfinderBundle in a Symfony 5.3 project. See deprecations (via logs or Symfony debug bar).

**Comment by helios-ag** [comment]
Thanks for report, already working on it

**Comment by helios-ag** [comment]
Should be fine now.
