### ISSUE TITLE
Error after all steps (Symfony 5)

### ISSUE THREAD

**Issue by CoolS2** [helios-ag/FMElfinderBundle#458]
ERROR:

There is no extension able to load the configuration for "elfinder" (in "config/packages/routing.yaml")

// composer.json

"helios-ag/fm-elfinder-bundle": "10.0.4"

// bundles.php

FM\ElfinderBundle\FMElfinderBundle::class => ['all' => true]

// routing.yaml

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yaml"

// security.yaml

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/efconnect, role: ROLE_USER }
         - { path: ^/elfinder, role: ROLE_USER }

// assets.yaml

fm_elfinder:
    instances:
        default:
            locale: '%locale%' 
            editor: ckeditor 
            relative_path: false 
            connector:
                roots:     
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

**Comment by CoolS2** [comment]
Resolved:

1. Remove elfinder from routing.yaml
2. Create file fm_elfinder.yaml and set configuration from guide
3. Set locale parameter %kernel.default_locale%

**Comment by helios-ag** [comment]
Cool :)
