### ISSUE TITLE
Directory removed in public after composer install

### ISSUE THREAD

**Issue by Jasonlgrd** [helios-ag/FMElfinderBundle#459]
Hello,

When i execute 
`composer install` or `bin/console assets:install public`
The folder fmelfinder in public/bundles is automatically removed. 
I'm obligatory execute `bin/console elfinder:install` after `composer install` everytime

Thank you,
Sorry for my english !

**Comment by entobvba** [comment]
Workaround: modify your composer.json so every time elfinder is automatically installed:

```
  "scripts": {
    "auto-scripts": {
      "cache:clear": "symfony-cmd",
      "assets:install %PUBLIC_DIR%": "symfony-cmd",
      "elfinder:install -q": "symfony-cmd" //Runs after assets:install
    },
    "post-install-cmd": [
      "@auto-scripts"
    ],
    "post-update-cmd": [
      "@auto-scripts"
    ]
  },
```

**Comment by Jasonlgrd** [comment]
Thanks for response !

It's functional for me, good ! 😁
