### ISSUE TITLE
Deprecation in Symfony 5.4: "...ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration

### ISSUE THREAD

**Issue by DavidGodefroid** [helios-ag/FMElfinderBundle#461]
In FM\ElfinderBundle\DependencyInjection\Configuration

> Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "FM\ElfinderBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by helios-ag** [comment]
https://github.com/helios-ag/FMElfinderBundle/blob/main/src/DependencyInjection/Configuration.php#L14
Resolved, should be fine now. Thanks for raising issue.
