### ISSUE TITLE
Considering tagging a new release

### ISSUE THREAD

**Issue by Kocal** [helios-ag/FMElfinderBundle#463]
Hi!

We want to migrate our application to Symfony Flex 2, however we got stuck when running `composer require symfony/flex symfony/runtime -W` due to the hard dependency to symfony/flex 1.*:
```
symfony composer require symfony/flex symfony/runtime -W
Using version ^2.0 for symfony/flex
./composer.json has been updated
Running composer update symfony/flex symfony/runtime --with-all-dependencies
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - helios-ag/fm-elfinder-bundle is locked to version 10.1 and an update of this package was not requested.
    - helios-ag/fm-elfinder-bundle 10.1 requires symfony/flex 1.* -> found symfony/flex[v1.0.0, ..., v1.17.6] but it conflicts with your root composer.json require (^2.0).
```

It has been fixed in #452, but sadly there is no new realse since.

Would it be possible to tagging a new release? Thanks!

**Comment by helios-ag** [comment]
Hi @Kocal, sure I can tag it, unfortunately I didn't have time to resolve deprecations.

**Comment by helios-ag** [comment]
Tagged as 11.0, hope it helps. https://github.com/helios-ag/FMElfinderBundle/releases/tag/11.0

**Comment by Kocal** [comment]
Hi @helios-ag, and thanks for your reactivity!

Installing 11.0 successfully worked to install Symfony Flex 2.0.
