### ISSUE TITLE
Symfony 6.0

### ISSUE THREAD

**Issue by FluffyDiscord** [helios-ag/FMElfinderBundle#464]
**Short description of what this feature will allow to do:**
Add support for symfony 6.0

**Example of how to use this feature**
package.json addition should be probably enough

**Comment by burakcakirel** [comment]
Thanks for raising the issue @FluffyDiscord 

@helios-ag Thanks for the great project. 
I'd like to make it compatible with Symfony 6.

Could you please guide me? @helios-ag 
I'm pleased to send a PR with the changes and we can discuss it. 

I'm stuck on the following error after fixing some minor deprecations

```
You cannot use the "renderView" method if the Twig Bundle is not available. Try running "composer require symfony/twig-bundle". 
in FMElfinderBundle/src/Controller/ElFinderController.php (line 44)
```

**Comment by helios-ag** [comment]
hi guys, I opened PR, need to fix failing tests, will fix tomorrow, and tag new release.

**Comment by helios-ag** [comment]
Tagged as [12.1](https://github.com/helios-ag/FMElfinderBundle/releases/tag/12.1)
