### ISSUE TITLE
configuration can be found here Flysystem 404

### ISSUE THREAD

**Issue by grekpg** [helios-ag/FMElfinderBundle#476]
in page https://github.com/helios-ag/FMElfinderBundle/blob/main/docs/advanced-configuration.md#flysystem-configuration 

link to the Example configuration can be found here [Flysystem](https://github.com/helios-ag/FMElfinderBundle/blob/main/Resources/doc/flysystem.md) 

give 404 not found

**Comment by johanadivare** [comment]
I can confirm this is already resolved
