### ISSUE TITLE
 Data exceeds the maximum allowed size.

### ISSUE THREAD

**Issue by firasmatoussi** [helios-ag/FMElfinderBundle#479]
Hello, when trying to upload file, it shows me the error "Data exceeds the maximum allowed size." 

while searching for the problem, I've tried to manage my php.ini with max_file_uploads, upload_max_filesize and file_uploads like I found in other solution, but it keeps showing me the same error.

The is no other solution to solve this issue ???
Btw, I'm using the FMElfinderBundle 12.1 
And here is my config for the bundle
```
fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            cors_support: true
            locale: en # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            relative_path: false #default true, will produce absolute urls to specified file(s)
            connector:
                debug: true
                roots: 
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        show_hidden: false
                        upload_allow: [ 'all' ]
                        upload_max_size: 10M 
```

**Comment by helios-ag** [comment]
hi @firasmatoussi
check also [post_max_size](https://www.php.net/manual/en/ini.core.php#ini.post-max-size)
