### ISSUE TITLE
Updating to 12.2.2 returns a script error

### ISSUE THREAD

**Issue by UlrichHP** [helios-ag/FMElfinderBundle#491]
**Describe the bug**
I updated the package to 12.2.2 and now elfinder is no longer working.

There is a script error and when looking at the missing js files, the package tries to load them from `elfinder/bundles/fmelfinder/...` instead of `public/bundles/fmelfinder/...`

Reverting to 12.2.1 seems to fix this issue.
I don't understand what can be causing it.

![Screenshot_20230209_121318](https://user-images.githubusercontent.com/27560999/217797395-cf160aef-f328-42ef-9b3e-3cff004de8a0.png)

![Screenshot_20230209_121336](https://user-images.githubusercontent.com/27560999/217797433-cd67f418-6841-4489-920a-720d91f69381.png)

**Comment by helios-ag** [comment]
Seems like it causes by https://github.com/helios-ag/FMElfinderBundle/pull/489

**Comment by UlrichHP** [comment]
@helios-ag yes, if i modify **baseUrl** with **asset('bundles/fmelfinder/js')** it is working as expected.

I don't know why but setting **mainUrl** in the Controller seems to modify the base folder and changes it to **elfinder** instead of **public**.

**Comment by UlrichHP** [comment]
@helios-ag I think i found the solution.

In **ElFinderController**, when defining **$mainUrl** at line 229, this is a relative path and not absolute. To make it absolute, a **/** must be added according to the [Symfony documentation](https://symfony.com/doc/current/components/asset.html#usage).

**Comment by helios-ag** [comment]
thank @UlrichHP !
going to merge

**Comment by helios-ag** [comment]
tagged as 12.2.3
