### ISSUE TITLE
error 404 for elfinder.min.js and editors.default.min.js when I open the elfinder popup  (Dev env OK but Prod env KO)

### ISSUE THREAD

**Issue by kegilko** [helios-ag/FMElfinderBundle#492]
**Describe the bug**
On symfony 6, I created a simple input form where a user can upload an image through an elfinder popup. All works perfectly on my local dev environment, but when I click on the elfinder field from my prod environment, the opened popup show 2 errors in alert popins : 

![image](https://user-images.githubusercontent.com/58623661/218286698-2aa4cbd1-369d-4c01-98d7-7e78805a7eeb.png)
![image](https://user-images.githubusercontent.com/58623661/218286702-96b871d6-169d-4768-a203-bbddb53e4d6a.png)

If I open the developer tools of my browser, I see theses 404 errors : 

![image](https://user-images.githubusercontent.com/58623661/218286740-afd065ae-3399-41d9-8cef-aab075e91738.png)

And, indeed, the paths are not good : 

- https://spacenomades.com/elfinder/bundles/fmelfinder/js/elfinder.min.js
- https://spacenomades.com/elfinder/bundles/fmelfinder/js/extras/editors.default.min.js

The goods paths are : 

- https://spacenomades.com/bundles/fmelfinder/js/elfinder.min.js
- https://spacenomades.com/bundles/fmelfinder/js/extras/editors.default.min.js

I don't understand why the 'elfinder' is added and I don't understand too why on my dev environment the paths of 'elfinder.min.js' and 'editors.default.min.js'..
And it's even stranger because, in another page I have a another form with CKeditor (CKeditor type form in Symfony) and I configure it for use elfinder (the value of the editor param in fm_elfinder.yaml is set to 'ckeditor' of course). In this case, all works fine. (in dev and prod env)
But as I explain before, when I click on an simple 'elfinder' field (the value of the editor param in fm_elfinder.yaml is set to 'simple'), the paths of the 'elfinder.min.js' and 'editors.default.min.js' files aren't not good in production environment..

In my fm_elfinder yaml file, I set the asset_path to : 

```yaml
fm_elfinder:
    assets_path: /bundles/fmelfinder # default is /assets, this is where css/js elfinder files are
```
And below, my public directory containing the '/bundles/fmelfinder' directory (created with the symfony command `./bin/console elfinder:install`) : 

![image](https://user-images.githubusercontent.com/58623661/218287270-cfbb02e1-3400-4340-a1ae-cbadfde01fea.png)

My FMElfinderBundle version is : 12.2.2

Thanks for any help !

**Comment by UlrichHP** [comment]
I had the same error, reported in the issue #491.
Updating to 12.2.3 should fix it.

**Comment by kegilko** [comment]
hann yes, indeed, the 12.2.3 fix the bug :D 
Thank you !
