### ISSUE TITLE
The assets for elfinder.min.js are giving 404 when using a different asset_path

### ISSUE THREAD

**Issue by johanadivare** [helios-ag/FMElfinderBundle#497]
**Describe the bug**
I have my `asset_path` configured to a different folder now with the recent changes: https://github.com/helios-ag/FMElfinderBundle/pull/493 i breaks it probably was already broke before this fix. Some more context: https://github.com/helios-ag/FMElfinderBundle/pull/493/files#r1162540304

**To Reproduce**
Have a `asset_path` defined to different folder then the default and check you get 404 when loading the assets.

**Comment by johanadivare** [comment]
Also can confirm that `/img/volume_icon_ftp.png` is also not loading for me

**Comment by enboig** [comment]
I am affected by this bug, when will it be merged and released?

**Comment by johanadivare** [comment]
The fix is in https://github.com/helios-ag/FMElfinderBundle/pull/509 but there is not much activity there atm.

For me i just locked my composer.json to older version for temporary fix to: `"helios-ag/fm-elfinder-bundle": "12.2.1",`

**Comment by enboig** [comment]
I was thinking of using https://github.com/symplify/vendor-patches

**Comment by helios-ag** [comment]
I can merge it guys, but didn't test for back compatiblity, if someone confirms, ok, will proceed

**Comment by JohJohan** [comment]
I can  confirm it works for me, but thats expected since i supplied the fix. When will we get a release? 


@enboig maybe you can confirm it works for you?

**Comment by JohJohan** [comment]
Ah sorry @jontjs it broke for you and probably others, i'm thinking changing the default `assets_path` to empty is also not an option as that could possible break other things i think.

**Comment by helios-ag** [comment]
@JohJohan @jontjs if you confirm we can make value empty by default
