### ISSUE TITLE
Invalid backend response

### ISSUE THREAD

**Issue by ladenise** [helios-ag/FMElfinderBundle#502]
**Describe the bug**
Since I updated from 12.2.3 to 12.3.1, I got "Invalid backend reponse" when elfinder opens.

**To Reproduce**
It happens every time I open Elfinder

**Comment by olia-bn** [comment]
Enabling CORS seems like a work-around rather than a fix, unless one is actually accessing the connector url from a different domain on the client side.

**Comment by bobvandevijver** [comment]
Fix has been released with 12.3.2.
