### ISSUE TITLE
Preview docs (pdf, docx, xlxx, etc)

### ISSUE THREAD

**Issue by Luvelnet** [helios-ag/FMElfinderBundle#517]
Hello,

I am trying to be able to view the docs, pdf, xlsx, etc. directly in ElFinder. I know that this functionality is already implemented, but I am getting the error because my files are not accessible through the web, they are "private" documents that require access with a login.

Is there any solution for this? For example, making a controller that searches for the file and returns it to you if you are logged in? And if so, how do we implement it in ElFinder?

Thank you

**Comment by helios-ag** [comment]
hi @Luvelnet 
Probably it's not possible with current bundle, but I think its would be possible with custom volume driver, which will authenticate by itself, something like getting basic auth in custom driver constructor
example driver: https://github.com/barryvdh/elfinder-flysystem-driver/blob/master/src/Driver.php

also check https://github.com/Studio-42/elFinder/issues/2252

**Comment by Luvelnet** [comment]
Thank you for your response.
