### ISSUE TITLE
Script error for "extras/editors.default.min"

### ISSUE THREAD

**Issue by alainjouve** [helios-ag/FMElfinderBundle#526]
Hello,
I'm using the latest version of helios-ag/FMElfinderBundle and it works fine on localhost server with  Symfony6.1; php8.2
I copied the entires configurations, files, ... from localhost to  the server.
But on the server, I get an error : Script error for "extras/editors.default.min" in a modale if I try to lunch the ELFinder explorer.

How can I resolve this issue?

Thanks 
Alain

**Comment by alainjouve** [comment]
Hello,
I  opened the console of my browser Firefox, an error message  appears which shows it's a path configuration mismatch. It seems the server doesn't write the good path :  https://www.concours2025.ampere2025.fr/bundles/fmelfinder/js/elfinder.min.js  instead writing :  https://www.concours2025.ampere2025.fr/public/bundles/fmelfinder/js/elfinder.min.js.
I did not find how to fix this with the assets_path in elfinder.yaml, it seems this param doesn't play role.
What have to do ?
Thanks 
Alain

**Comment by alainjouve** [comment]
I copied the elfinder directory in a directory /bundles/ on the root of serveur, in this way elfinder is working fine !
I think this issue may help others.
Greetings
Alain

**Comment by helios-ag** [comment]
@alainjouve thanks for sharing your solution!

**Comment by alainjouve** [comment]
Solution was found.
