### ISSUE TITLE
ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by xorgxx** [helios-ag/FMElfinderBundle#87]
newly i get this error : 

```
ReferenceError: $ is not defined
$('[data-type="elfinder-input-field"][id="neo_filesmanagerbundle_filesmanager_ur...
```
i deed not change nathink, have just det new bundle and new form : 
```
        $builder
            ->add('description')
            ->add('licence')
            ->add('namefile', 'ckeditor')
            ->add('extension')
            ->add('nbdownload')
            ->add('url','elfinder', array('instance'=>'form', 'enable'=>true))
            ->add('permission')
            ->add('md5')
            ->add('date', 'genemu_jquerydate' , array(
                'widget' => 'single_text'
              )
            )
            ->add('publish')
        ;
```
when i go on this page and i click on url to have librairie i have nathink.
the strange think, i have same button with function how call by ajax same form for update with inside "elfinder" and it work well on all but not ??
genemu and ckeditor work well

**Comment by Kalmac** [comment]
Hello,

I managed to let jquery on page footer with some code :

app/config/config.yml
```
twig:
    form:
        resources:
            - 'MyAppBundle:Form:fields.html.twig'
```
in src/My/AppBundle/Resources/Form/fields.html.twig
```
{% block elfinder_widget %}
<input type="text" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %} data-type="elfinder-input-field" />
{% if enable and instance is defined %}
    <script type="text/javascript">
        var elfinder_files = elfinder_files || {};
        elfinder_files['{{id}}'] = '{{path('elfinder', {'instance': instance })}}';
    </script>
{% endif %}
{% endblock %}
```

in base template after jquery insertion :
```javascript
<script type="text/javascript">
        var elfinder_files = elfinder_files || {};
        for(var key in files_images) {
            $('[data-type="elfinder-input-field"][id="' + key + '"]').on("click",function() {
                var childWin = window.open(elfinder_files[key] + '?id=' + key, "popupWindow", "height=450, width=900");
            });
        }

    function setValue(value, element_id) {
        $('[data-type="elfinder-input-field"]' + (element_id ? '[id="'+ element_id +'"]': '')).val(value);
    }
</script>
```

**Comment by helios-ag** [comment]
Hi @Kalmac thank you for sharing your solution.

**Comment by bgatellier** [comment]
Hi,

I had the same problem today, using latest Symfony2 (2.6.6 atm, IvoryCKEditorBundle
~3 and FMElfinderBundle ~5). I solved it with a more simple solution, but with changes in the *assets_js.html.twig* and *assets_css.html.twig* files of the bundle.

So here is my solution :
I changed
``` twig
<script src="{{ prefix }}/jquery/jquery.js"></script>
```
Into 
``` twig
<script src="{{ app.request.schemeAndHttpHost ~ app.request.basepath ~ prefix }}/jquery/jquery.js"></script>
```
And I changed every `<script>` and `<link>` tags for the 2 TWIG template files the same way.

And that's it ! It works well in my case.
The major drawback is that I will have to do this change each time the bundle will be updated...

Hope this solution will help someone in the future ;-)

**Comment by wadjeroudi** [comment]
You don't need to change the templates.
The variable "prefix" has been created for this case.

You need to set the variable "assets_path" in your elfinder config:

fm_elfinder:
    assets_path: '/subfolder/assets'
    instances:
        default:
...etc
