### ISSUE TITLE
Relative path image

### ISSUE THREAD

**Issue by gaet** [helios-ag/FMElfinderBundle#93]
Hello,

Nice work to this bundle!
I have a problem, when I upload image file with this bundle, he take the absolute path and not the relative path.
This is a problem because the website dont find the image with localhost path.

I don't undestand how to resolve this problem.
In config.yml I have put "uploads" folder in variable "path".

How set the relative path ?

Thanks you

**Comment by gaet** [comment]
I undestand that you say, and I can't modify a .htaccess, because he isn't public for me.

But I think isn't good to have "localhost" a web site, so in the textearea is the same.

If you registered localhost in a path, nobody can see the url. I say that because I learn this on my computer science study, but maybe it's wrong ....

And when I use Symfony 1.4 with Ckeditor and kcfinder, the path begin with racine of the serveur like "/webumrh/folderpublic/picture.png" for example.

**Comment by gaet** [comment]
I have make the override bundle and It's work fine !
I have create a global variable to make the "my_folder_prefix" path.

Thank you very much for your help.

**Comment by helios-ag** [comment]
You are welcome!
