### ISSUE TITLE
How to override the paste method

### ISSUE THREAD

**Issue by davidino** [helios-ag/FMElfinderBundle#98]
Hi 
my need is to execute a task when a `past` command is executed.

I see that past method is part of `Elfinder` Class but [since it is hard coded in the loader](https://github.com/helios-ag/FMElfinderBundle/blob/master/Loader/ElFinderLoader.php#L57) i cant inject a different class to overload this method

i also try to write a plugin catching the event `pre.paste`. But for me the problem is that if my task fail (return false) the paste command should not be executed ( or fail). [And the problem is that the command is always executed](https://github.com/helios-ag/ElFinderPHP/blob/master/src/ElFinder.php#L471) ... also when the pre task has failed.

So, what should i do ?
i cant see the proper way ? or there is no way, and i've to prepare a PR to inject a different Elfinder ( with my paste implementation ) inside the loader ... or something else ?

Thank you.

**Comment by helios-ag** [comment]
Well, that's an interesting question. In my opinion, it would be nice to have ability to override Loader.
But from other point of view, having the elfinder lib ability to interrupt execution of commands by controlling via plugins would be nice too. And sharing plugin might be useful for other users of elfinder.

**Comment by davidino** [comment]
I agree extend the plugins system is a good choice.
But, is there a way to inject a new Plugin ? because from the documentation i cant find any information.
It seems that we can recall just the plugins in the original repo

**Comment by helios-ag** [comment]
Hi David, in latest commit(475450ee307c25fcdcbec30d6522ce534444d105), i've made loader service overridable, readme section [here](https://github.com/helios-ag/FMElfinderBundle#custom-loader).
Returning to question about extending plugins, as you can see we have ElFinderBridge class under FM\ElfinderBundle\Bridge namespace, which allows to replace built-in (ElfinderPHP lib provided drivers, like LocalVolumeDriver) volume drivers by symfony service, the same thing i think can be done with Plugins. But probably will require to override [getPluginInstance](https://github.com/helios-ag/ElFinderPHP/blob/master/src/ElFinder.php#L581) method.
