### ISSUE TITLE
Wrong url when select the picture

### ISSUE THREAD

**Issue by abdielcs** [helios-ag/FMElfinderBundle#99]
I already configured Symfony2 with IvoryCKEditor and FMElfinder, following the default configuration.  I can upload and see all the files correctly. But when I select the file in the dialog window it seems like the url referenced by the selected file is wrong. I only see a red icon of error in the preview. I get the js error 
"NetworkError: 404 Not Found - http://localhost/symfony/2.6/Symfony/public_html/app_dev.php/admin/news/uploads%5Cfoto1.JPG"
 
![error](https://cloud.githubusercontent.com/assets/5825680/5824729/4d9b09c8-a0b4-11e4-9868-08460cd718ad.jpg)

The right url should by "http://localhost/symfony/2.6/Symfony/public_html/uploads/foto1.JPG"

In the production enviroment without using app.php the obtained url still contain "/admin/news" and the character "\" . so still broken.

**Comment by yplam** [comment]
You can use the follow config option to fix this:

relative_path: false

That's because in Resources/views/Elfinder/ckeditor.html.twig

```
                if (funcNum) {
                    {% if relative_path %}
                        window.opener.CKEDITOR.tools.callFunction(funcNum, file.path);
                    {% else %}
                        window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);
                    {% endif %}
                    window.close();
                }
```

and the file.path is wrong

**Comment by meshenka** [comment]
Got same issue with the following config

`̀`̀`̀
fm_elfinder:
   instances:
        default:
            relative_path: false
            locale: %locale% 
            editor: ckeditor # other choices are tinymce or simple
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/wysiwyg
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
`̀`̀`̀

the relative_path: false is required and partialy fix the problem: now the html markup generated is absolute path, i would prefer to have de href="/uploads/wysiwyg/xy.jpg" instead of an absolute URL

**Comment by yplam** [comment]
Another way to fix this:

Config relative_path: false

Create and config your own ElFinderConfigurationReader service

Extends the ElFinderConfigurationReader class, override the getConfiguration method, and change the URL option.

```

use FM\ElfinderBundle\Configuration\ElFinderConfigurationReader as BaseElFinderConfigurationReader;
/**
 *
 * Class ElFinderConfigurationReader
 */
class ElFinderConfigurationReader extends BaseElFinderConfigurationReader
{
   /**
     * @param $instance
     * @return array
     */
    public function getConfiguration($instance)
    {
        ...
           
            $driverOptions = array(
                'driver'        => $parameter['driver'],
                'service'       => $driver,
                'disabled'      => $parameter['disabled'],
                'plugin'        => $parameter['plugin'],
                'path'          => $path . '/',
                'URL'           => '/' .$path . '/',  // change the URL option.
                'accessControl' => array($this, 'access'),
                'uploadAllow'   => $parameter['upload_allow'],
                'uploadDeny'    => $parameter['upload_deny'],
                'uploadMaxSize' => $parameter['upload_max_size']
            );

    ...
    }
}

```
